coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        threshold: 1% # allow this much decrease on project

    patch:
      default:
        target: 80%
        threshold: 0%
        only_pulls: true

comment:
  layout: "reach, diff, files"
  behavior: default  # update if exists else create new

ignore:
  - "*.md"
  - "audits/"
  - "assets/"
  - "scripts/"
  - "client/api/"
  - "client/cmd/"
  - "client/config/"
  - "client/proto/"
  - "client/server/"
  - "contracts/"
  - "**/*.pb.go"
  - "**/*.pulsar.go"
  - "**/module.go"
  - "**/depinject.go"
