version: "2"
run:
  go: "1.24"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocognit
    - godox
    - gomoddirectives
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - nonamedreturns
    - prealloc
    - tagliatelle
    - tparallel
    - varnamelen
    - wsl
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    forbidigo:
      forbid:
        - pattern: fmt\.Print.*(# Avoid debug logging)?
        - pattern: fmt\.Errorf.*(# Prefer lib/errors.Wrap)?
        - pattern: prometheus\.New.*(# Prefer promauto)?
    govet:
      enable-all: true
    importas:
      alias:
        - pkg: github.com/cometbft/cometbft/crypto/secp256k1
          alias: k1
      no-unaliased: true
    misspell:
      locale: US
    nlreturn:
      block-size: 2
    nolintlint:
      require-explanation: true
      require-specific: true
    paralleltest:
      ignore-missing: true
      ignore-missing-subtests: true
    revive:
      severity: warning
      enable-all-rules: true
      rules:
        - name: file-header
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: banned-characters
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: function-length
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: argument-limit
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: imports-blocklist
          arguments:
            - log
            - github.com/gogo/protobuf/proto
            - github.com/stretchr/testify/assert
            - golang.org/x/exp/slices
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println
    staticcheck:
      checks:
        - all
        - -SA1019
    testpackage:
      skip-regexp: internal_test\.go
    wrapcheck:
      ignore-sigs:
        - github.com/piplabs/story/
        - google.golang.org/grpc/status
        - github.com/ethereum/go-ethereum
        - Errorf
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - contextcheck
          - dupl
          - gosec
          - maintidx
          - perfsprint
          - revive
          - wrapcheck
        path: (.*)(_test|tutil|scripts)(.*)
      - linters:
          - perfsprint
        path: (.*)(e2e)(.*)
      - linters:
          - forbidigo
        path: (.*)(scripts|cli)(.*)
      - path: (.+)\.go$
        text: add-constant
      - path: (.+)\.go$
        text: fieldalignment
      - path: (.+)\.go$
        text: 'shadow: declaration of'
      - path: (.+)\.go$
        text: shadows an import name
      - path: (.+)\.go$
        text: 'ifElseChain: rewrite if-else to switch statement'
      - path: (.+)\.go$
        text: 'nested-structs: no nested structs are allowed'
      - path: (.+)\.go$
        text: confusing-naming
      - path: (.+)\.go$
        text: flag-parameter
      - path: (.+)\.go$
        text: 'G306: Expect WriteFile permissions to be 0600 or less'
      - path: (.+)\.go$
        text: 'exported: type name will be used as module.Module'
      - path: (.+)\.go$
        text: 'defer: prefer not to defer chains of function calls'
      - path: (.+)\.go$
        text: 'G601: Implicit memory aliasing in for loop'
      - path: (.+)\.go$
        text: 'loopclosure: loop variable'
      - path: (.+)\.go$
        text: Range statement for test
      - path: (.+)\.go$
        text: 'range-val-address: suspicious assignment of'
      - path: (.+)\.go$
        text: exporting a pointer for the loop variable snapshot
      - path: (.+)\.go$
        text: has no field or method
      - path: (.+)\.go$
        text: integer overflow conversion

      - text: 'use pointer receiver and non-pointer receiver'            # We prefer non-pointers, but require pointer receivers for unmarshalling.
        linters: [ recvcheck ]
      - text: 'avoid meaningless package names'
        linters: [ revive ]
      - text: 'avoid package names that conflict with Go standard library package names' # Use errors package for Story error
        linters: [ revive ]
      - text: 'avoid inline error handling using' # allow inline error handling
        linters: [ noinlineerr ]
    paths:
      - .*\.pb\.go$
      - contracts/bindings/*
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - prefix(golang.org)
        - prefix(cosmossdk.io)
        - prefix(github.com)
        - prefix(github.com/piplabs)
        - prefix(github.com/piplabs/story)
        - default
        - blank
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - contracts/bindings/*
      - third_party$
      - builtin$
      - examples$
