syntax = "proto3";
package story.dkg.v1.types;

option go_package = "github.com/piplabs/story/client/x/dkg/types";

enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0;
  EVENT_TYPE_BEGIN_INITIALIZATION = 1;
  EVENT_TYPE_BEGIN_DEALING = 2;
  EVENT_TYPE_BEGIN_PROCESS_DEALS = 3;
  EVENT_TYPE_BEGIN_PROCESS_RESPONSES = 4;
  EVENT_TYPE_BEGIN_FINALIZATION = 5;
  EVENT_TYPE_DKG_FINALIZED = 6;
  EVENT_TYPE_BEGIN_PROCESS_JUSTIFICATIONS = 7;
}

message EventBeginInitialization {
  uint32 round = 1;
  uint32 start_block_height = 2;
  repeated string active_validators = 3;
}

message EventBeginDealing {
  uint32 round = 1;
}

message EventBeginProcessDeals {
  uint32 round = 1;
  uint32 num_deals = 2;
}

message EventBeginProcessResponses {
  uint32 round = 1;
  uint32 num_responses = 2;
}

message EventBeginProcessJustifications {
  uint32 round = 1;
  uint32 num_justifications = 2;
}

message EventBeginFinalization {
  uint32 round = 1;
}

message EventDKGFinalized {
  uint32 round = 1;
}

message EventDKGCommitteeRewarded {
  uint32 round = 1;
  uint32 member_count = 2;
  string total_reward = 3;
  string per_member_reward = 4;
  string remaining_ubi = 5;
}
