// Code generated by MockGen. DO NOT EDIT.
// Source: client/x/dkg/types/tee.pb.go
//
// Generated by this command:
//
//	mockgen -source=client/x/dkg/types/tee.pb.go -package testutil -destination=client/x/dkg/testutil/tee_client_mock.go TEEClient
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	types "github.com/piplabs/story/client/x/dkg/types"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockTEEClient is a mock of TEEClient interface.
type MockTEEClient struct {
	ctrl     *gomock.Controller
	recorder *MockTEEClientMockRecorder
	isgomock struct{}
}

// MockTEEClientMockRecorder is the mock recorder for MockTEEClient.
type MockTEEClientMockRecorder struct {
	mock *MockTEEClient
}

// NewMockTEEClient creates a new mock instance.
func NewMockTEEClient(ctrl *gomock.Controller) *MockTEEClient {
	mock := &MockTEEClient{ctrl: ctrl}
	mock.recorder = &MockTEEClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTEEClient) EXPECT() *MockTEEClientMockRecorder {
	return m.recorder
}

// FinalizeDKG mocks base method.
func (m *MockTEEClient) FinalizeDKG(ctx context.Context, in *types.FinalizeDKGRequest, opts ...grpc.CallOption) (*types.FinalizeDKGResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FinalizeDKG", varargs...)
	ret0, _ := ret[0].(*types.FinalizeDKGResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeDKG indicates an expected call of FinalizeDKG.
func (mr *MockTEEClientMockRecorder) FinalizeDKG(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeDKG", reflect.TypeOf((*MockTEEClient)(nil).FinalizeDKG), varargs...)
}

// GenerateAndSealKey mocks base method.
func (m *MockTEEClient) GenerateAndSealKey(ctx context.Context, in *types.GenerateAndSealKeyRequest, opts ...grpc.CallOption) (*types.GenerateAndSealKeyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateAndSealKey", varargs...)
	ret0, _ := ret[0].(*types.GenerateAndSealKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAndSealKey indicates an expected call of GenerateAndSealKey.
func (mr *MockTEEClientMockRecorder) GenerateAndSealKey(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAndSealKey", reflect.TypeOf((*MockTEEClient)(nil).GenerateAndSealKey), varargs...)
}

// GenerateDeals mocks base method.
func (m *MockTEEClient) GenerateDeals(ctx context.Context, in *types.GenerateDealsRequest, opts ...grpc.CallOption) (*types.GenerateDealsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateDeals", varargs...)
	ret0, _ := ret[0].(*types.GenerateDealsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDeals indicates an expected call of GenerateDeals.
func (mr *MockTEEClientMockRecorder) GenerateDeals(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDeals", reflect.TypeOf((*MockTEEClient)(nil).GenerateDeals), varargs...)
}

// PartialDecryptTDH2 mocks base method.
func (m *MockTEEClient) PartialDecryptTDH2(ctx context.Context, in *types.PartialDecryptTDH2Request, opts ...grpc.CallOption) (*types.PartialDecryptTDH2Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PartialDecryptTDH2", varargs...)
	ret0, _ := ret[0].(*types.PartialDecryptTDH2Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PartialDecryptTDH2 indicates an expected call of PartialDecryptTDH2.
func (mr *MockTEEClientMockRecorder) PartialDecryptTDH2(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialDecryptTDH2", reflect.TypeOf((*MockTEEClient)(nil).PartialDecryptTDH2), varargs...)
}

// ProcessDeals mocks base method.
func (m *MockTEEClient) ProcessDeals(ctx context.Context, in *types.ProcessDealRequest, opts ...grpc.CallOption) (*types.ProcessDealResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProcessDeals", varargs...)
	ret0, _ := ret[0].(*types.ProcessDealResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessDeals indicates an expected call of ProcessDeals.
func (mr *MockTEEClientMockRecorder) ProcessDeals(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessDeals", reflect.TypeOf((*MockTEEClient)(nil).ProcessDeals), varargs...)
}

// ProcessResponses mocks base method.
func (m *MockTEEClient) ProcessResponses(ctx context.Context, in *types.ProcessResponsesRequest, opts ...grpc.CallOption) (*types.ProcessResponsesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProcessResponses", varargs...)
	ret0, _ := ret[0].(*types.ProcessResponsesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessResponses indicates an expected call of ProcessResponses.
func (mr *MockTEEClientMockRecorder) ProcessResponses(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessResponses", reflect.TypeOf((*MockTEEClient)(nil).ProcessResponses), varargs...)
}

// SetupDKGNetwork mocks base method.
func (m *MockTEEClient) SetupDKGNetwork(ctx context.Context, in *types.SetupDKGNetworkRequest, opts ...grpc.CallOption) (*types.SetupDKGNetworkResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetupDKGNetwork", varargs...)
	ret0, _ := ret[0].(*types.SetupDKGNetworkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupDKGNetwork indicates an expected call of SetupDKGNetwork.
func (mr *MockTEEClientMockRecorder) SetupDKGNetwork(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupDKGNetwork", reflect.TypeOf((*MockTEEClient)(nil).SetupDKGNetwork), varargs...)
}

// VerifyRawQuote mocks base method.
func (m *MockTEEClient) VerifyRawQuote(ctx context.Context, in *types.VerifyRawQuoteRequest, opts ...grpc.CallOption) (*types.VerifyRawQuoteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "VerifyRawQuote", varargs...)
	ret0, _ := ret[0].(*types.VerifyRawQuoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRawQuote indicates an expected call of VerifyRawQuote.
func (mr *MockTEEClientMockRecorder) VerifyRawQuote(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRawQuote", reflect.TypeOf((*MockTEEClient)(nil).VerifyRawQuote), varargs...)
}

// MockTEEServer is a mock of TEEServer interface.
type MockTEEServer struct {
	ctrl     *gomock.Controller
	recorder *MockTEEServerMockRecorder
	isgomock struct{}
}

// MockTEEServerMockRecorder is the mock recorder for MockTEEServer.
type MockTEEServerMockRecorder struct {
	mock *MockTEEServer
}

// NewMockTEEServer creates a new mock instance.
func NewMockTEEServer(ctrl *gomock.Controller) *MockTEEServer {
	mock := &MockTEEServer{ctrl: ctrl}
	mock.recorder = &MockTEEServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTEEServer) EXPECT() *MockTEEServerMockRecorder {
	return m.recorder
}

// FinalizeDKG mocks base method.
func (m *MockTEEServer) FinalizeDKG(arg0 context.Context, arg1 *types.FinalizeDKGRequest) (*types.FinalizeDKGResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeDKG", arg0, arg1)
	ret0, _ := ret[0].(*types.FinalizeDKGResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeDKG indicates an expected call of FinalizeDKG.
func (mr *MockTEEServerMockRecorder) FinalizeDKG(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeDKG", reflect.TypeOf((*MockTEEServer)(nil).FinalizeDKG), arg0, arg1)
}

// GenerateAndSealKey mocks base method.
func (m *MockTEEServer) GenerateAndSealKey(arg0 context.Context, arg1 *types.GenerateAndSealKeyRequest) (*types.GenerateAndSealKeyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAndSealKey", arg0, arg1)
	ret0, _ := ret[0].(*types.GenerateAndSealKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAndSealKey indicates an expected call of GenerateAndSealKey.
func (mr *MockTEEServerMockRecorder) GenerateAndSealKey(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAndSealKey", reflect.TypeOf((*MockTEEServer)(nil).GenerateAndSealKey), arg0, arg1)
}

// GenerateDeals mocks base method.
func (m *MockTEEServer) GenerateDeals(arg0 context.Context, arg1 *types.GenerateDealsRequest) (*types.GenerateDealsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDeals", arg0, arg1)
	ret0, _ := ret[0].(*types.GenerateDealsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDeals indicates an expected call of GenerateDeals.
func (mr *MockTEEServerMockRecorder) GenerateDeals(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDeals", reflect.TypeOf((*MockTEEServer)(nil).GenerateDeals), arg0, arg1)
}

// PartialDecryptTDH2 mocks base method.
func (m *MockTEEServer) PartialDecryptTDH2(arg0 context.Context, arg1 *types.PartialDecryptTDH2Request) (*types.PartialDecryptTDH2Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialDecryptTDH2", arg0, arg1)
	ret0, _ := ret[0].(*types.PartialDecryptTDH2Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PartialDecryptTDH2 indicates an expected call of PartialDecryptTDH2.
func (mr *MockTEEServerMockRecorder) PartialDecryptTDH2(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialDecryptTDH2", reflect.TypeOf((*MockTEEServer)(nil).PartialDecryptTDH2), arg0, arg1)
}

// ProcessDeals mocks base method.
func (m *MockTEEServer) ProcessDeals(arg0 context.Context, arg1 *types.ProcessDealRequest) (*types.ProcessDealResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessDeals", arg0, arg1)
	ret0, _ := ret[0].(*types.ProcessDealResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessDeals indicates an expected call of ProcessDeals.
func (mr *MockTEEServerMockRecorder) ProcessDeals(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessDeals", reflect.TypeOf((*MockTEEServer)(nil).ProcessDeals), arg0, arg1)
}

// ProcessResponses mocks base method.
func (m *MockTEEServer) ProcessResponses(arg0 context.Context, arg1 *types.ProcessResponsesRequest) (*types.ProcessResponsesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessResponses", arg0, arg1)
	ret0, _ := ret[0].(*types.ProcessResponsesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessResponses indicates an expected call of ProcessResponses.
func (mr *MockTEEServerMockRecorder) ProcessResponses(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessResponses", reflect.TypeOf((*MockTEEServer)(nil).ProcessResponses), arg0, arg1)
}

// SetupDKGNetwork mocks base method.
func (m *MockTEEServer) SetupDKGNetwork(arg0 context.Context, arg1 *types.SetupDKGNetworkRequest) (*types.SetupDKGNetworkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupDKGNetwork", arg0, arg1)
	ret0, _ := ret[0].(*types.SetupDKGNetworkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupDKGNetwork indicates an expected call of SetupDKGNetwork.
func (mr *MockTEEServerMockRecorder) SetupDKGNetwork(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupDKGNetwork", reflect.TypeOf((*MockTEEServer)(nil).SetupDKGNetwork), arg0, arg1)
}

// VerifyRawQuote mocks base method.
func (m *MockTEEServer) VerifyRawQuote(arg0 context.Context, arg1 *types.VerifyRawQuoteRequest) (*types.VerifyRawQuoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRawQuote", arg0, arg1)
	ret0, _ := ret[0].(*types.VerifyRawQuoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRawQuote indicates an expected call of VerifyRawQuote.
func (mr *MockTEEServerMockRecorder) VerifyRawQuote(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRawQuote", reflect.TypeOf((*MockTEEServer)(nil).VerifyRawQuote), arg0, arg1)
}
