// Code generated by MockGen. DO NOT EDIT.
// Source: client/x/dkg/types/tee.pb.go
//
// Generated by this command:
//
//	mockgen -source=client/x/dkg/types/tee.pb.go -package testutil -destination=client/x/dkg/testutil/tee_client_mock.go TEEClient
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	types "github.com/piplabs/story/client/x/dkg/types"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockKernelClient is a mock of KernelClient interface.
type MockKernelClient struct {
	ctrl     *gomock.Controller
	recorder *MockKernelClientMockRecorder
	isgomock struct{}
}

// MockKernelClientMockRecorder is the mock recorder for MockKernelClient.
type MockKernelClientMockRecorder struct {
	mock *MockKernelClient
}

// NewMockKernelClient creates a new mock instance.
func NewMockKernelClient(ctrl *gomock.Controller) *MockKernelClient {
	mock := &MockKernelClient{ctrl: ctrl}
	mock.recorder = &MockKernelClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKernelClient) EXPECT() *MockKernelClientMockRecorder {
	return m.recorder
}

// FinalizeDKG mocks base method.
func (m *MockKernelClient) FinalizeDKG(ctx context.Context, in *types.FinalizeDKGRequest, opts ...grpc.CallOption) (*types.FinalizeDKGResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FinalizeDKG", varargs...)
	ret0, _ := ret[0].(*types.FinalizeDKGResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeDKG indicates an expected call of FinalizeDKG.
func (mr *MockKernelClientMockRecorder) FinalizeDKG(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeDKG", reflect.TypeOf((*MockKernelClient)(nil).FinalizeDKG), varargs...)
}

// GenerateAndSealKey mocks base method.
func (m *MockKernelClient) GenerateAndSealKey(ctx context.Context, in *types.GenerateAndSealKeyRequest, opts ...grpc.CallOption) (*types.GenerateAndSealKeyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateAndSealKey", varargs...)
	ret0, _ := ret[0].(*types.GenerateAndSealKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAndSealKey indicates an expected call of GenerateAndSealKey.
func (mr *MockKernelClientMockRecorder) GenerateAndSealKey(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAndSealKey", reflect.TypeOf((*MockKernelClient)(nil).GenerateAndSealKey), varargs...)
}

// GenerateDeals mocks base method.
func (m *MockKernelClient) GenerateDeals(ctx context.Context, in *types.GenerateDealsRequest, opts ...grpc.CallOption) (*types.GenerateDealsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateDeals", varargs...)
	ret0, _ := ret[0].(*types.GenerateDealsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDeals indicates an expected call of GenerateDeals.
func (mr *MockKernelClientMockRecorder) GenerateDeals(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDeals", reflect.TypeOf((*MockKernelClient)(nil).GenerateDeals), varargs...)
}

// GetCodeCommitment mocks base method.
func (m *MockKernelClient) GetCodeCommitment(ctx context.Context, in *types.GetCodeCommitmentRequest, opts ...grpc.CallOption) (*types.GetCodeCommitmentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCodeCommitment", varargs...)
	ret0, _ := ret[0].(*types.GetCodeCommitmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCodeCommitment indicates an expected call of GetCodeCommitment.
func (mr *MockKernelClientMockRecorder) GetCodeCommitment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeCommitment", reflect.TypeOf((*MockKernelClient)(nil).GetCodeCommitment), varargs...)
}

// PartialDecryptTDH2 mocks base method.
func (m *MockKernelClient) PartialDecryptTDH2(ctx context.Context, in *types.PartialDecryptTDH2Request, opts ...grpc.CallOption) (*types.PartialDecryptTDH2Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PartialDecryptTDH2", varargs...)
	ret0, _ := ret[0].(*types.PartialDecryptTDH2Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PartialDecryptTDH2 indicates an expected call of PartialDecryptTDH2.
func (mr *MockKernelClientMockRecorder) PartialDecryptTDH2(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialDecryptTDH2", reflect.TypeOf((*MockKernelClient)(nil).PartialDecryptTDH2), varargs...)
}

// ProcessDeals mocks base method.
func (m *MockKernelClient) ProcessDeals(ctx context.Context, in *types.ProcessDealsRequest, opts ...grpc.CallOption) (*types.ProcessDealsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProcessDeals", varargs...)
	ret0, _ := ret[0].(*types.ProcessDealsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessDeals indicates an expected call of ProcessDeals.
func (mr *MockKernelClientMockRecorder) ProcessDeals(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessDeals", reflect.TypeOf((*MockKernelClient)(nil).ProcessDeals), varargs...)
}

// ProcessJustification mocks base method.
func (m *MockKernelClient) ProcessJustification(ctx context.Context, in *types.ProcessJustificationRequest, opts ...grpc.CallOption) (*types.ProcessJustificationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProcessJustification", varargs...)
	ret0, _ := ret[0].(*types.ProcessJustificationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessJustification indicates an expected call of ProcessJustification.
func (mr *MockKernelClientMockRecorder) ProcessJustification(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessJustification", reflect.TypeOf((*MockKernelClient)(nil).ProcessJustification), varargs...)
}

// ProcessResponses mocks base method.
func (m *MockKernelClient) ProcessResponses(ctx context.Context, in *types.ProcessResponsesRequest, opts ...grpc.CallOption) (*types.ProcessResponsesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProcessResponses", varargs...)
	ret0, _ := ret[0].(*types.ProcessResponsesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessResponses indicates an expected call of ProcessResponses.
func (mr *MockKernelClientMockRecorder) ProcessResponses(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessResponses", reflect.TypeOf((*MockKernelClient)(nil).ProcessResponses), varargs...)
}

// MockKernelServer is a mock of KernelServer interface.
type MockKernelServer struct {
	ctrl     *gomock.Controller
	recorder *MockKernelServerMockRecorder
	isgomock struct{}
}

// MockKernelServerMockRecorder is the mock recorder for MockKernelServer.
type MockKernelServerMockRecorder struct {
	mock *MockKernelServer
}

// NewMockKernelServer creates a new mock instance.
func NewMockKernelServer(ctrl *gomock.Controller) *MockKernelServer {
	mock := &MockKernelServer{ctrl: ctrl}
	mock.recorder = &MockKernelServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKernelServer) EXPECT() *MockKernelServerMockRecorder {
	return m.recorder
}

// FinalizeDKG mocks base method.
func (m *MockKernelServer) FinalizeDKG(arg0 context.Context, arg1 *types.FinalizeDKGRequest) (*types.FinalizeDKGResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeDKG", arg0, arg1)
	ret0, _ := ret[0].(*types.FinalizeDKGResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeDKG indicates an expected call of FinalizeDKG.
func (mr *MockKernelServerMockRecorder) FinalizeDKG(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeDKG", reflect.TypeOf((*MockKernelServer)(nil).FinalizeDKG), arg0, arg1)
}

// GenerateAndSealKey mocks base method.
func (m *MockKernelServer) GenerateAndSealKey(arg0 context.Context, arg1 *types.GenerateAndSealKeyRequest) (*types.GenerateAndSealKeyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAndSealKey", arg0, arg1)
	ret0, _ := ret[0].(*types.GenerateAndSealKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAndSealKey indicates an expected call of GenerateAndSealKey.
func (mr *MockKernelServerMockRecorder) GenerateAndSealKey(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAndSealKey", reflect.TypeOf((*MockKernelServer)(nil).GenerateAndSealKey), arg0, arg1)
}

// GenerateDeals mocks base method.
func (m *MockKernelServer) GenerateDeals(arg0 context.Context, arg1 *types.GenerateDealsRequest) (*types.GenerateDealsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDeals", arg0, arg1)
	ret0, _ := ret[0].(*types.GenerateDealsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDeals indicates an expected call of GenerateDeals.
func (mr *MockKernelServerMockRecorder) GenerateDeals(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDeals", reflect.TypeOf((*MockKernelServer)(nil).GenerateDeals), arg0, arg1)
}

// GetCodeCommitment mocks base method.
func (m *MockKernelServer) GetCodeCommitment(arg0 context.Context, arg1 *types.GetCodeCommitmentRequest) (*types.GetCodeCommitmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodeCommitment", arg0, arg1)
	ret0, _ := ret[0].(*types.GetCodeCommitmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCodeCommitment indicates an expected call of GetCodeCommitment.
func (mr *MockKernelServerMockRecorder) GetCodeCommitment(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeCommitment", reflect.TypeOf((*MockKernelServer)(nil).GetCodeCommitment), arg0, arg1)
}

// PartialDecryptTDH2 mocks base method.
func (m *MockKernelServer) PartialDecryptTDH2(arg0 context.Context, arg1 *types.PartialDecryptTDH2Request) (*types.PartialDecryptTDH2Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialDecryptTDH2", arg0, arg1)
	ret0, _ := ret[0].(*types.PartialDecryptTDH2Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PartialDecryptTDH2 indicates an expected call of PartialDecryptTDH2.
func (mr *MockKernelServerMockRecorder) PartialDecryptTDH2(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialDecryptTDH2", reflect.TypeOf((*MockKernelServer)(nil).PartialDecryptTDH2), arg0, arg1)
}

// ProcessDeals mocks base method.
func (m *MockKernelServer) ProcessDeals(arg0 context.Context, arg1 *types.ProcessDealsRequest) (*types.ProcessDealsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessDeals", arg0, arg1)
	ret0, _ := ret[0].(*types.ProcessDealsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessDeals indicates an expected call of ProcessDeals.
func (mr *MockKernelServerMockRecorder) ProcessDeals(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessDeals", reflect.TypeOf((*MockKernelServer)(nil).ProcessDeals), arg0, arg1)
}

// ProcessJustification mocks base method.
func (m *MockKernelServer) ProcessJustification(arg0 context.Context, arg1 *types.ProcessJustificationRequest) (*types.ProcessJustificationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessJustification", arg0, arg1)
	ret0, _ := ret[0].(*types.ProcessJustificationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessJustification indicates an expected call of ProcessJustification.
func (mr *MockKernelServerMockRecorder) ProcessJustification(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessJustification", reflect.TypeOf((*MockKernelServer)(nil).ProcessJustification), arg0, arg1)
}

// ProcessResponses mocks base method.
func (m *MockKernelServer) ProcessResponses(arg0 context.Context, arg1 *types.ProcessResponsesRequest) (*types.ProcessResponsesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessResponses", arg0, arg1)
	ret0, _ := ret[0].(*types.ProcessResponsesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessResponses indicates an expected call of ProcessResponses.
func (mr *MockKernelServerMockRecorder) ProcessResponses(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessResponses", reflect.TypeOf((*MockKernelServer)(nil).ProcessResponses), arg0, arg1)
}
