// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: story/dkg/v1/types/event.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED             EventType = 0
	EventType_EVENT_TYPE_BEGIN_INITIALIZATION    EventType = 1
	EventType_EVENT_TYPE_BEGIN_DEALING           EventType = 2
	EventType_EVENT_TYPE_BEGIN_PROCESS_DEALS     EventType = 3
	EventType_EVENT_TYPE_BEGIN_PROCESS_RESPONSES EventType = 4
	EventType_EVENT_TYPE_BEGIN_FINALIZATION      EventType = 5
	EventType_EVENT_TYPE_DKG_FINALIZED           EventType = 6
)

var EventType_name = map[int32]string{
	0: "EVENT_TYPE_UNSPECIFIED",
	1: "EVENT_TYPE_BEGIN_INITIALIZATION",
	2: "EVENT_TYPE_BEGIN_DEALING",
	3: "EVENT_TYPE_BEGIN_PROCESS_DEALS",
	4: "EVENT_TYPE_BEGIN_PROCESS_RESPONSES",
	5: "EVENT_TYPE_BEGIN_FINALIZATION",
	6: "EVENT_TYPE_DKG_FINALIZED",
}

var EventType_value = map[string]int32{
	"EVENT_TYPE_UNSPECIFIED":             0,
	"EVENT_TYPE_BEGIN_INITIALIZATION":    1,
	"EVENT_TYPE_BEGIN_DEALING":           2,
	"EVENT_TYPE_BEGIN_PROCESS_DEALS":     3,
	"EVENT_TYPE_BEGIN_PROCESS_RESPONSES": 4,
	"EVENT_TYPE_BEGIN_FINALIZATION":      5,
	"EVENT_TYPE_DKG_FINALIZED":           6,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_801f42319f883aee, []int{0}
}

type EventBeginInitialization struct {
	Mrenclave        []byte   `protobuf:"bytes,1,opt,name=mrenclave,proto3" json:"mrenclave,omitempty"`
	Round            uint32   `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	StartBlock       uint32   `protobuf:"varint,3,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	ActiveValidators []string `protobuf:"bytes,4,rep,name=active_validators,json=activeValidators,proto3" json:"active_validators,omitempty"`
}

func (m *EventBeginInitialization) Reset()         { *m = EventBeginInitialization{} }
func (m *EventBeginInitialization) String() string { return proto.CompactTextString(m) }
func (*EventBeginInitialization) ProtoMessage()    {}
func (*EventBeginInitialization) Descriptor() ([]byte, []int) {
	return fileDescriptor_801f42319f883aee, []int{0}
}
func (m *EventBeginInitialization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBeginInitialization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBeginInitialization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBeginInitialization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBeginInitialization.Merge(m, src)
}
func (m *EventBeginInitialization) XXX_Size() int {
	return m.Size()
}
func (m *EventBeginInitialization) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBeginInitialization.DiscardUnknown(m)
}

var xxx_messageInfo_EventBeginInitialization proto.InternalMessageInfo

func (m *EventBeginInitialization) GetMrenclave() []byte {
	if m != nil {
		return m.Mrenclave
	}
	return nil
}

func (m *EventBeginInitialization) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *EventBeginInitialization) GetStartBlock() uint32 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *EventBeginInitialization) GetActiveValidators() []string {
	if m != nil {
		return m.ActiveValidators
	}
	return nil
}

type EventBeginDealing struct {
	Mrenclave []byte `protobuf:"bytes,1,opt,name=mrenclave,proto3" json:"mrenclave,omitempty"`
	Round     uint32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
}

func (m *EventBeginDealing) Reset()         { *m = EventBeginDealing{} }
func (m *EventBeginDealing) String() string { return proto.CompactTextString(m) }
func (*EventBeginDealing) ProtoMessage()    {}
func (*EventBeginDealing) Descriptor() ([]byte, []int) {
	return fileDescriptor_801f42319f883aee, []int{1}
}
func (m *EventBeginDealing) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBeginDealing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBeginDealing.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBeginDealing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBeginDealing.Merge(m, src)
}
func (m *EventBeginDealing) XXX_Size() int {
	return m.Size()
}
func (m *EventBeginDealing) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBeginDealing.DiscardUnknown(m)
}

var xxx_messageInfo_EventBeginDealing proto.InternalMessageInfo

func (m *EventBeginDealing) GetMrenclave() []byte {
	if m != nil {
		return m.Mrenclave
	}
	return nil
}

func (m *EventBeginDealing) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

type EventBeginProcessDeals struct {
	Mrenclave []byte `protobuf:"bytes,1,opt,name=mrenclave,proto3" json:"mrenclave,omitempty"`
	Round     uint32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Deals     []Deal `protobuf:"bytes,3,rep,name=deals,proto3" json:"deals"`
}

func (m *EventBeginProcessDeals) Reset()         { *m = EventBeginProcessDeals{} }
func (m *EventBeginProcessDeals) String() string { return proto.CompactTextString(m) }
func (*EventBeginProcessDeals) ProtoMessage()    {}
func (*EventBeginProcessDeals) Descriptor() ([]byte, []int) {
	return fileDescriptor_801f42319f883aee, []int{2}
}
func (m *EventBeginProcessDeals) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBeginProcessDeals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBeginProcessDeals.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBeginProcessDeals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBeginProcessDeals.Merge(m, src)
}
func (m *EventBeginProcessDeals) XXX_Size() int {
	return m.Size()
}
func (m *EventBeginProcessDeals) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBeginProcessDeals.DiscardUnknown(m)
}

var xxx_messageInfo_EventBeginProcessDeals proto.InternalMessageInfo

func (m *EventBeginProcessDeals) GetMrenclave() []byte {
	if m != nil {
		return m.Mrenclave
	}
	return nil
}

func (m *EventBeginProcessDeals) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *EventBeginProcessDeals) GetDeals() []Deal {
	if m != nil {
		return m.Deals
	}
	return nil
}

type EventBeginProcessResponses struct {
	Mrenclave []byte     `protobuf:"bytes,1,opt,name=mrenclave,proto3" json:"mrenclave,omitempty"`
	Round     uint32     `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Responses []Response `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses"`
}

func (m *EventBeginProcessResponses) Reset()         { *m = EventBeginProcessResponses{} }
func (m *EventBeginProcessResponses) String() string { return proto.CompactTextString(m) }
func (*EventBeginProcessResponses) ProtoMessage()    {}
func (*EventBeginProcessResponses) Descriptor() ([]byte, []int) {
	return fileDescriptor_801f42319f883aee, []int{3}
}
func (m *EventBeginProcessResponses) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBeginProcessResponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBeginProcessResponses.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBeginProcessResponses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBeginProcessResponses.Merge(m, src)
}
func (m *EventBeginProcessResponses) XXX_Size() int {
	return m.Size()
}
func (m *EventBeginProcessResponses) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBeginProcessResponses.DiscardUnknown(m)
}

var xxx_messageInfo_EventBeginProcessResponses proto.InternalMessageInfo

func (m *EventBeginProcessResponses) GetMrenclave() []byte {
	if m != nil {
		return m.Mrenclave
	}
	return nil
}

func (m *EventBeginProcessResponses) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *EventBeginProcessResponses) GetResponses() []Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

type EventBeginFinalization struct {
	Mrenclave []byte `protobuf:"bytes,1,opt,name=mrenclave,proto3" json:"mrenclave,omitempty"`
	Round     uint32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
}

func (m *EventBeginFinalization) Reset()         { *m = EventBeginFinalization{} }
func (m *EventBeginFinalization) String() string { return proto.CompactTextString(m) }
func (*EventBeginFinalization) ProtoMessage()    {}
func (*EventBeginFinalization) Descriptor() ([]byte, []int) {
	return fileDescriptor_801f42319f883aee, []int{4}
}
func (m *EventBeginFinalization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBeginFinalization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBeginFinalization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBeginFinalization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBeginFinalization.Merge(m, src)
}
func (m *EventBeginFinalization) XXX_Size() int {
	return m.Size()
}
func (m *EventBeginFinalization) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBeginFinalization.DiscardUnknown(m)
}

var xxx_messageInfo_EventBeginFinalization proto.InternalMessageInfo

func (m *EventBeginFinalization) GetMrenclave() []byte {
	if m != nil {
		return m.Mrenclave
	}
	return nil
}

func (m *EventBeginFinalization) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

type EventDKGFinalized struct {
	Mrenclave []byte `protobuf:"bytes,1,opt,name=mrenclave,proto3" json:"mrenclave,omitempty"`
	Round     uint32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
}

func (m *EventDKGFinalized) Reset()         { *m = EventDKGFinalized{} }
func (m *EventDKGFinalized) String() string { return proto.CompactTextString(m) }
func (*EventDKGFinalized) ProtoMessage()    {}
func (*EventDKGFinalized) Descriptor() ([]byte, []int) {
	return fileDescriptor_801f42319f883aee, []int{5}
}
func (m *EventDKGFinalized) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventDKGFinalized) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventDKGFinalized.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventDKGFinalized) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDKGFinalized.Merge(m, src)
}
func (m *EventDKGFinalized) XXX_Size() int {
	return m.Size()
}
func (m *EventDKGFinalized) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDKGFinalized.DiscardUnknown(m)
}

var xxx_messageInfo_EventDKGFinalized proto.InternalMessageInfo

func (m *EventDKGFinalized) GetMrenclave() []byte {
	if m != nil {
		return m.Mrenclave
	}
	return nil
}

func (m *EventDKGFinalized) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func init() {
	proto.RegisterEnum("story.dkg.v1.types.EventType", EventType_name, EventType_value)
	proto.RegisterType((*EventBeginInitialization)(nil), "story.dkg.v1.types.EventBeginInitialization")
	proto.RegisterType((*EventBeginDealing)(nil), "story.dkg.v1.types.EventBeginDealing")
	proto.RegisterType((*EventBeginProcessDeals)(nil), "story.dkg.v1.types.EventBeginProcessDeals")
	proto.RegisterType((*EventBeginProcessResponses)(nil), "story.dkg.v1.types.EventBeginProcessResponses")
	proto.RegisterType((*EventBeginFinalization)(nil), "story.dkg.v1.types.EventBeginFinalization")
	proto.RegisterType((*EventDKGFinalized)(nil), "story.dkg.v1.types.EventDKGFinalized")
}

func init() { proto.RegisterFile("story/dkg/v1/types/event.proto", fileDescriptor_801f42319f883aee) }

var fileDescriptor_801f42319f883aee = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xc1, 0x6a, 0xdb, 0x30,
	0x1c, 0xc6, 0xa3, 0xa6, 0x2d, 0x44, 0xdd, 0xc0, 0x15, 0xa5, 0x98, 0xd0, 0x39, 0x99, 0x07, 0x23,
	0xac, 0x60, 0xd3, 0x6d, 0x0f, 0xb0, 0xa4, 0x56, 0x82, 0x68, 0x70, 0x82, 0x9d, 0x15, 0xd6, 0x4b,
	0x70, 0x6c, 0xe1, 0x89, 0xb8, 0x96, 0xb1, 0x55, 0xb3, 0xec, 0xb8, 0x27, 0x18, 0x3b, 0xef, 0x81,
	0x7a, 0xec, 0x71, 0xa7, 0x31, 0x92, 0x87, 0xd8, 0x75, 0x58, 0x4e, 0x9a, 0xb2, 0x74, 0x97, 0xec,
	0x62, 0xec, 0xff, 0xf7, 0xe9, 0xf3, 0xcf, 0xfe, 0xf8, 0x43, 0x2d, 0x13, 0x3c, 0x9d, 0x99, 0xc1,
	0x34, 0x34, 0xf3, 0x33, 0x53, 0xcc, 0x12, 0x9a, 0x99, 0x34, 0xa7, 0xb1, 0x30, 0x92, 0x94, 0x0b,
	0x8e, 0x90, 0xd4, 0x8d, 0x60, 0x1a, 0x1a, 0xf9, 0x99, 0x21, 0xf5, 0xfa, 0x51, 0xc8, 0x43, 0x2e,
	0x65, 0xb3, 0xb8, 0x2b, 0x9d, 0xf5, 0xc7, 0x92, 0xe4, 0xb5, 0xd4, 0xf5, 0xef, 0x00, 0xaa, 0xb8,
	0x48, 0xee, 0xd0, 0x90, 0xc5, 0x24, 0x66, 0x82, 0x79, 0x11, 0xfb, 0xec, 0x09, 0xc6, 0x63, 0x74,
	0x02, 0x6b, 0xd7, 0x29, 0x8d, 0xfd, 0xc8, 0xcb, 0xa9, 0x0a, 0x9a, 0xa0, 0xf5, 0xc4, 0x59, 0x0f,
	0xd0, 0x11, 0xdc, 0x4b, 0xf9, 0x4d, 0x1c, 0xa8, 0x3b, 0x4d, 0xd0, 0x7a, 0xea, 0x94, 0x0f, 0xa8,
	0x01, 0x0f, 0x32, 0xe1, 0xa5, 0x62, 0x3c, 0x89, 0xb8, 0x3f, 0x55, 0xab, 0x52, 0x83, 0x72, 0xd4,
	0x29, 0x26, 0xe8, 0x14, 0x1e, 0x7a, 0xbe, 0x60, 0x39, 0x1d, 0xe7, 0x5e, 0xc4, 0x02, 0x4f, 0xf0,
	0x34, 0x53, 0x77, 0x9b, 0xd5, 0x56, 0xcd, 0x51, 0x4a, 0xe1, 0xf2, 0x7e, 0xae, 0xf7, 0xe0, 0xe1,
	0x9a, 0xce, 0xa2, 0x5e, 0xc4, 0xe2, 0x70, 0x1b, 0x2c, 0xfd, 0x0b, 0x80, 0xc7, 0xeb, 0xa4, 0x61,
	0xca, 0x7d, 0x9a, 0x65, 0x45, 0x60, 0xb6, 0xd5, 0x57, 0xbe, 0x85, 0x7b, 0x41, 0x71, 0x58, 0xad,
	0x36, 0xab, 0xad, 0x83, 0xd7, 0xaa, 0xb1, 0x59, 0x88, 0x51, 0xa4, 0x77, 0x76, 0x6f, 0x7f, 0x36,
	0x2a, 0x4e, 0x69, 0xd6, 0xbf, 0x01, 0x58, 0xdf, 0x80, 0x70, 0x68, 0x96, 0xf0, 0x38, 0xa3, 0xdb,
	0x81, 0xbc, 0x83, 0xb5, 0x74, 0x15, 0xb0, 0x84, 0x39, 0x79, 0x0c, 0x66, 0xf5, 0x96, 0x25, 0xd0,
	0xfa, 0x90, 0xde, 0x7f, 0xf8, 0x63, 0xba, 0x2c, 0xfe, 0xaf, 0xfa, 0xef, 0x0b, 0xb3, 0x2e, 0x7a,
	0xcb, 0x2c, 0x1a, 0x6c, 0x13, 0xf4, 0xea, 0x37, 0x80, 0x35, 0x99, 0x34, 0x9a, 0x25, 0x14, 0xd5,
	0xe1, 0x31, 0xbe, 0xc4, 0xf6, 0x68, 0x3c, 0xfa, 0x30, 0xc4, 0xe3, 0xf7, 0xb6, 0x3b, 0xc4, 0xe7,
	0xa4, 0x4b, 0xb0, 0xa5, 0x54, 0xd0, 0x0b, 0xd8, 0x78, 0xa0, 0x75, 0x70, 0x8f, 0xd8, 0x63, 0x62,
	0x93, 0x11, 0x69, 0xf7, 0xc9, 0x55, 0x7b, 0x44, 0x06, 0xb6, 0x02, 0xd0, 0x09, 0x54, 0x37, 0x4c,
	0x16, 0x6e, 0xf7, 0x89, 0xdd, 0x53, 0x76, 0x90, 0x0e, 0xb5, 0x0d, 0x75, 0xe8, 0x0c, 0xce, 0xb1,
	0xeb, 0x4a, 0x97, 0xab, 0x54, 0xd1, 0x4b, 0xa8, 0xff, 0xd3, 0xe3, 0x60, 0x77, 0x38, 0xb0, 0x5d,
	0xec, 0x2a, 0xbb, 0xe8, 0x39, 0x7c, 0xb6, 0xe1, 0xeb, 0x12, 0x7b, 0x0d, 0xb3, 0xf7, 0x17, 0x8c,
	0x75, 0xd1, 0x5b, 0x19, 0xb0, 0xa5, 0xec, 0x77, 0xf0, 0xed, 0x5c, 0x03, 0x77, 0x73, 0x0d, 0xfc,
	0x9a, 0x6b, 0xe0, 0xeb, 0x42, 0xab, 0xdc, 0x2d, 0xb4, 0xca, 0x8f, 0x85, 0x56, 0xb9, 0x3a, 0x0d,
	0x99, 0xf8, 0x78, 0x33, 0x31, 0x7c, 0x7e, 0x6d, 0x26, 0x2c, 0x89, 0xbc, 0x49, 0x66, 0x96, 0xfb,
	0xed, 0x47, 0x8c, 0xc6, 0xc2, 0xfc, 0x24, 0x17, 0x5d, 0x36, 0x3e, 0xd9, 0x97, 0x0b, 0xfe, 0xe6,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xa4, 0x1b, 0x2b, 0x4c, 0x04, 0x00, 0x00,
}

func (m *EventBeginInitialization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBeginInitialization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBeginInitialization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ActiveValidators) > 0 {
		for iNdEx := len(m.ActiveValidators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ActiveValidators[iNdEx])
			copy(dAtA[i:], m.ActiveValidators[iNdEx])
			i = encodeVarintEvent(dAtA, i, uint64(len(m.ActiveValidators[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.StartBlock != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.StartBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.Round != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBeginDealing) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBeginDealing) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBeginDealing) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Round != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBeginProcessDeals) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBeginProcessDeals) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBeginProcessDeals) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Deals) > 0 {
		for iNdEx := len(m.Deals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Deals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Round != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBeginProcessResponses) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBeginProcessResponses) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBeginProcessResponses) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Responses) > 0 {
		for iNdEx := len(m.Responses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Responses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Round != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBeginFinalization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBeginFinalization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBeginFinalization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Round != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventDKGFinalized) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventDKGFinalized) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventDKGFinalized) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Round != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventBeginInitialization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovEvent(uint64(m.Round))
	}
	if m.StartBlock != 0 {
		n += 1 + sovEvent(uint64(m.StartBlock))
	}
	if len(m.ActiveValidators) > 0 {
		for _, s := range m.ActiveValidators {
			l = len(s)
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func (m *EventBeginDealing) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovEvent(uint64(m.Round))
	}
	return n
}

func (m *EventBeginProcessDeals) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovEvent(uint64(m.Round))
	}
	if len(m.Deals) > 0 {
		for _, e := range m.Deals {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func (m *EventBeginProcessResponses) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovEvent(uint64(m.Round))
	}
	if len(m.Responses) > 0 {
		for _, e := range m.Responses {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func (m *EventBeginFinalization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovEvent(uint64(m.Round))
	}
	return n
}

func (m *EventDKGFinalized) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovEvent(uint64(m.Round))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventBeginInitialization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBeginInitialization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBeginInitialization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = append(m.Mrenclave[:0], dAtA[iNdEx:postIndex]...)
			if m.Mrenclave == nil {
				m.Mrenclave = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlock", wireType)
			}
			m.StartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveValidators", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActiveValidators = append(m.ActiveValidators, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBeginDealing) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBeginDealing: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBeginDealing: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = append(m.Mrenclave[:0], dAtA[iNdEx:postIndex]...)
			if m.Mrenclave == nil {
				m.Mrenclave = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBeginProcessDeals) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBeginProcessDeals: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBeginProcessDeals: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = append(m.Mrenclave[:0], dAtA[iNdEx:postIndex]...)
			if m.Mrenclave == nil {
				m.Mrenclave = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deals = append(m.Deals, Deal{})
			if err := m.Deals[len(m.Deals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBeginProcessResponses) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBeginProcessResponses: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBeginProcessResponses: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = append(m.Mrenclave[:0], dAtA[iNdEx:postIndex]...)
			if m.Mrenclave == nil {
				m.Mrenclave = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Responses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Responses = append(m.Responses, Response{})
			if err := m.Responses[len(m.Responses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBeginFinalization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBeginFinalization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBeginFinalization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = append(m.Mrenclave[:0], dAtA[iNdEx:postIndex]...)
			if m.Mrenclave == nil {
				m.Mrenclave = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventDKGFinalized) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventDKGFinalized: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventDKGFinalized: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = append(m.Mrenclave[:0], dAtA[iNdEx:postIndex]...)
			if m.Mrenclave == nil {
				m.Mrenclave = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
