// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: story/dkg/v1/types/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
// All timeouts are in seconds.
type Params struct {
	RegistrationPeriod uint32 `protobuf:"varint,1,opt,name=registration_period,json=registrationPeriod,proto3" json:"registration_period,omitempty" yaml:"registration_period"`
	ChallengePeriod    uint32 `protobuf:"varint,2,opt,name=challenge_period,json=challengePeriod,proto3" json:"challenge_period,omitempty" yaml:"challenge_period"`
	DealingPeriod      uint32 `protobuf:"varint,3,opt,name=dealing_period,json=dealingPeriod,proto3" json:"dealing_period,omitempty" yaml:"dealing_period"`
	FinalizationPeriod uint32 `protobuf:"varint,4,opt,name=finalization_period,json=finalizationPeriod,proto3" json:"finalization_period,omitempty" yaml:"finalization_period"`
	ActivePeriod       uint32 `protobuf:"varint,5,opt,name=active_period,json=activePeriod,proto3" json:"active_period,omitempty" yaml:"active_period"`
	ComplaintPeriod    uint32 `protobuf:"varint,6,opt,name=complaint_period,json=complaintPeriod,proto3" json:"complaint_period,omitempty" yaml:"complaint_period"`
	MinCommitteeSize   uint32 `protobuf:"varint,7,opt,name=min_committee_size,json=minCommitteeSize,proto3" json:"min_committee_size,omitempty" yaml:"min_committee_size"`
	// latest TEE mrenclave
	Mrenclave []byte `protobuf:"bytes,8,opt,name=mrenclave,proto3" json:"mrenclave,omitempty" yaml:"mrenclave"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9e79a1c09b3ec30, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetRegistrationPeriod() uint32 {
	if m != nil {
		return m.RegistrationPeriod
	}
	return 0
}

func (m *Params) GetChallengePeriod() uint32 {
	if m != nil {
		return m.ChallengePeriod
	}
	return 0
}

func (m *Params) GetDealingPeriod() uint32 {
	if m != nil {
		return m.DealingPeriod
	}
	return 0
}

func (m *Params) GetFinalizationPeriod() uint32 {
	if m != nil {
		return m.FinalizationPeriod
	}
	return 0
}

func (m *Params) GetActivePeriod() uint32 {
	if m != nil {
		return m.ActivePeriod
	}
	return 0
}

func (m *Params) GetComplaintPeriod() uint32 {
	if m != nil {
		return m.ComplaintPeriod
	}
	return 0
}

func (m *Params) GetMinCommitteeSize() uint32 {
	if m != nil {
		return m.MinCommitteeSize
	}
	return 0
}

func (m *Params) GetMrenclave() []byte {
	if m != nil {
		return m.Mrenclave
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "story.dkg.v1.types.Params")
}

func init() { proto.RegisterFile("story/dkg/v1/types/params.proto", fileDescriptor_d9e79a1c09b3ec30) }

var fileDescriptor_d9e79a1c09b3ec30 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x63, 0x28, 0x01, 0x46, 0x0d, 0x44, 0xd3, 0x20, 0xdc, 0x22, 0xec, 0x6a, 0x56, 0x95,
	0x90, 0x3c, 0x2a, 0xec, 0x90, 0x90, 0x50, 0x10, 0x6c, 0x58, 0xb4, 0x32, 0x3b, 0x36, 0xd1, 0xc4,
	0x1e, 0xa6, 0x47, 0x9d, 0x8b, 0x65, 0x0f, 0x16, 0xc9, 0x53, 0xf0, 0x40, 0x3c, 0x00, 0xcb, 0x2e,
	0x59, 0x59, 0x28, 0x79, 0x03, 0x3f, 0x01, 0xca, 0xd8, 0x0e, 0xb9, 0xed, 0xec, 0xff, 0x7c, 0xf3,
	0x49, 0xe7, 0xe8, 0x47, 0x61, 0x61, 0x4d, 0x3e, 0xa3, 0xe9, 0xad, 0xa0, 0xe5, 0x25, 0xb5, 0xb3,
	0x8c, 0x17, 0x34, 0x63, 0x39, 0x53, 0x45, 0x94, 0xe5, 0xc6, 0x1a, 0x8c, 0x1d, 0x10, 0xa5, 0xb7,
	0x22, 0x2a, 0x2f, 0x23, 0x07, 0x9c, 0x8d, 0x84, 0x11, 0xc6, 0x8d, 0xe9, 0xea, 0xab, 0x21, 0xc9,
	0xaf, 0x23, 0xd4, 0xbf, 0x76, 0x4f, 0xf1, 0x15, 0x3a, 0xc9, 0xb9, 0x80, 0xc2, 0xe6, 0xcc, 0x82,
	0xd1, 0x93, 0x8c, 0xe7, 0x60, 0x52, 0xdf, 0x3b, 0xf7, 0x2e, 0x06, 0xe3, 0xa0, 0xae, 0xc2, 0xb3,
	0x19, 0x53, 0xf2, 0x2d, 0x39, 0x00, 0x91, 0x18, 0x6f, 0xa6, 0xd7, 0x2e, 0xc4, 0x9f, 0xd0, 0x30,
	0xb9, 0x61, 0x52, 0x72, 0x2d, 0x78, 0x67, 0xbb, 0xe7, 0x6c, 0x2f, 0xea, 0x2a, 0x7c, 0xde, 0xd8,
	0x76, 0x09, 0x12, 0x3f, 0x5d, 0x47, 0xad, 0xe7, 0x3d, 0x7a, 0x92, 0x72, 0x26, 0x41, 0x8b, 0xce,
	0x72, 0xdf, 0x59, 0x4e, 0xeb, 0x2a, 0x7c, 0xd6, 0x58, 0xb6, 0xe7, 0x24, 0x1e, 0xb4, 0x41, 0x6b,
	0xb8, 0x42, 0x27, 0xdf, 0x40, 0x33, 0x09, 0xf3, 0xad, 0xd5, 0x8e, 0x76, 0x57, 0x3b, 0x00, 0x91,
	0x18, 0x6f, 0xa6, 0xad, 0xf0, 0x1d, 0x1a, 0xb0, 0xc4, 0x42, 0xb9, 0xde, 0xeb, 0x81, 0x53, 0xf9,
	0x75, 0x15, 0x8e, 0x1a, 0xd5, 0xd6, 0x98, 0xc4, 0xc7, 0xcd, 0xff, 0xc6, 0x65, 0x8c, 0xca, 0x24,
	0x03, 0x6d, 0x3b, 0x43, 0x7f, 0xef, 0x32, 0x3b, 0xc4, 0xea, 0x32, 0x5d, 0xd4, 0x7a, 0x3e, 0x23,
	0xac, 0x40, 0x4f, 0x12, 0xa3, 0x14, 0x58, 0xcb, 0xf9, 0xa4, 0x80, 0x39, 0xf7, 0x1f, 0x3a, 0xd3,
	0xcb, 0xba, 0x0a, 0x4f, 0x1b, 0xd3, 0x3e, 0x43, 0xe2, 0xa1, 0x02, 0xfd, 0xa1, 0xcb, 0xbe, 0xc0,
	0x9c, 0xe3, 0xd7, 0xe8, 0xb1, 0xca, 0xb9, 0x4e, 0x24, 0x2b, 0xb9, 0xff, 0xe8, 0xdc, 0xbb, 0x38,
	0x1e, 0x8f, 0xea, 0x2a, 0x1c, 0xb6, 0x8e, 0x6e, 0x44, 0xe2, 0xff, 0xd8, 0xf8, 0xe3, 0xef, 0x45,
	0xe0, 0xdd, 0x2d, 0x02, 0xef, 0xef, 0x22, 0xf0, 0x7e, 0x2e, 0x83, 0xde, 0xdd, 0x32, 0xe8, 0xfd,
	0x59, 0x06, 0xbd, 0xaf, 0xaf, 0x04, 0xd8, 0x9b, 0xef, 0xd3, 0x28, 0x31, 0x8a, 0x66, 0x90, 0x49,
	0x36, 0x2d, 0x68, 0x53, 0xdb, 0x44, 0x02, 0xd7, 0x96, 0xfe, 0x70, 0xfd, 0x75, 0xdd, 0x9c, 0xf6,
	0x5d, 0x19, 0xdf, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x9c, 0x58, 0xb9, 0xd9, 0x02, 0x00,
	0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0x42
	}
	if m.MinCommitteeSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinCommitteeSize))
		i--
		dAtA[i] = 0x38
	}
	if m.ComplaintPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ComplaintPeriod))
		i--
		dAtA[i] = 0x30
	}
	if m.ActivePeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActivePeriod))
		i--
		dAtA[i] = 0x28
	}
	if m.FinalizationPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FinalizationPeriod))
		i--
		dAtA[i] = 0x20
	}
	if m.DealingPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DealingPeriod))
		i--
		dAtA[i] = 0x18
	}
	if m.ChallengePeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ChallengePeriod))
		i--
		dAtA[i] = 0x10
	}
	if m.RegistrationPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RegistrationPeriod))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RegistrationPeriod != 0 {
		n += 1 + sovParams(uint64(m.RegistrationPeriod))
	}
	if m.ChallengePeriod != 0 {
		n += 1 + sovParams(uint64(m.ChallengePeriod))
	}
	if m.DealingPeriod != 0 {
		n += 1 + sovParams(uint64(m.DealingPeriod))
	}
	if m.FinalizationPeriod != 0 {
		n += 1 + sovParams(uint64(m.FinalizationPeriod))
	}
	if m.ActivePeriod != 0 {
		n += 1 + sovParams(uint64(m.ActivePeriod))
	}
	if m.ComplaintPeriod != 0 {
		n += 1 + sovParams(uint64(m.ComplaintPeriod))
	}
	if m.MinCommitteeSize != 0 {
		n += 1 + sovParams(uint64(m.MinCommitteeSize))
	}
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationPeriod", wireType)
			}
			m.RegistrationPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistrationPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengePeriod", wireType)
			}
			m.ChallengePeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengePeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealingPeriod", wireType)
			}
			m.DealingPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DealingPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizationPeriod", wireType)
			}
			m.FinalizationPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizationPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivePeriod", wireType)
			}
			m.ActivePeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivePeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ComplaintPeriod", wireType)
			}
			m.ComplaintPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ComplaintPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCommitteeSize", wireType)
			}
			m.MinCommitteeSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinCommitteeSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = append(m.Mrenclave[:0], dAtA[iNdEx:postIndex]...)
			if m.Mrenclave == nil {
				m.Mrenclave = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
