// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: story/dkg/v1/types/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DKGRegStatus int32

const (
	DKGRegStatusUnspecified DKGRegStatus = 0
	DKGRegStatusVerified    DKGRegStatus = 2
	DKGRegStatusNetworkSet  DKGRegStatus = 3
	DKGRegStatusFinalized   DKGRegStatus = 4
)

var DKGRegStatus_name = map[int32]string{
	0: "DKG_REG_STATUS_UNSPECIFIED",
	2: "DKG_REG_STATUS_VERIFIED",
	3: "DKG_REG_STATUS_NETWORK_SET",
	4: "DKG_REG_STATUS_FINALIZED",
}

var DKGRegStatus_value = map[string]int32{
	"DKG_REG_STATUS_UNSPECIFIED": 0,
	"DKG_REG_STATUS_VERIFIED":    2,
	"DKG_REG_STATUS_NETWORK_SET": 3,
	"DKG_REG_STATUS_FINALIZED":   4,
}

func (x DKGRegStatus) String() string {
	return proto.EnumName(DKGRegStatus_name, int32(x))
}

func (DKGRegStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{0}
}

type DKGStage int32

const (
	DKGStageUnspecified         DKGStage = 0
	DKGStageRegistration        DKGStage = 1
	DKGStageNetworkSet          DKGStage = 2
	DKGStageNetworkSetCompleted DKGStage = 3
	DKGStageDealing             DKGStage = 4
	DKGStageFinalization        DKGStage = 5
	DKGStageActive              DKGStage = 6
)

var DKGStage_name = map[int32]string{
	0: "DKG_STAGE_UNSPECIFIED",
	1: "DKG_STAGE_REGISTRATION",
	2: "DKG_STAGE_NETWORK_SET",
	3: "DKG_STAGE_NETWORK_SET_COMPLETED",
	4: "DKG_STAGE_DEALING",
	5: "DKG_STAGE_FINALIZATION",
	6: "DKG_STAGE_ACTIVE",
}

var DKGStage_value = map[string]int32{
	"DKG_STAGE_UNSPECIFIED":           0,
	"DKG_STAGE_REGISTRATION":          1,
	"DKG_STAGE_NETWORK_SET":           2,
	"DKG_STAGE_NETWORK_SET_COMPLETED": 3,
	"DKG_STAGE_DEALING":               4,
	"DKG_STAGE_FINALIZATION":          5,
	"DKG_STAGE_ACTIVE":                6,
}

func (x DKGStage) String() string {
	return proto.EnumName(DKGStage_name, int32(x))
}

func (DKGStage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{1}
}

type DKGNetwork struct {
	Mrenclave  []byte `protobuf:"bytes,1,opt,name=mrenclave,proto3" json:"mrenclave,omitempty" yaml:"mrenclave"`
	Round      uint32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty" yaml:"round"`
	StartBlock int64  `protobuf:"varint,3,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty" yaml:"start_block"`
	// list of active validators' evm addresses
	ActiveValSet []string `protobuf:"bytes,4,rep,name=active_val_set,json=activeValSet,proto3" json:"active_val_set,omitempty" yaml:"active_val_set"`
	Total        uint32   `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty" yaml:"total"`
	Threshold    uint32   `protobuf:"varint,6,opt,name=threshold,proto3" json:"threshold,omitempty" yaml:"threshold"`
	Stage        DKGStage `protobuf:"varint,7,opt,name=stage,proto3,enum=story.dkg.v1.types.DKGStage" json:"stage,omitempty" yaml:"stage"`
}

func (m *DKGNetwork) Reset()         { *m = DKGNetwork{} }
func (m *DKGNetwork) String() string { return proto.CompactTextString(m) }
func (*DKGNetwork) ProtoMessage()    {}
func (*DKGNetwork) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{0}
}
func (m *DKGNetwork) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DKGNetwork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DKGNetwork.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DKGNetwork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGNetwork.Merge(m, src)
}
func (m *DKGNetwork) XXX_Size() int {
	return m.Size()
}
func (m *DKGNetwork) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGNetwork.DiscardUnknown(m)
}

var xxx_messageInfo_DKGNetwork proto.InternalMessageInfo

func (m *DKGNetwork) GetMrenclave() []byte {
	if m != nil {
		return m.Mrenclave
	}
	return nil
}

func (m *DKGNetwork) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *DKGNetwork) GetStartBlock() int64 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *DKGNetwork) GetActiveValSet() []string {
	if m != nil {
		return m.ActiveValSet
	}
	return nil
}

func (m *DKGNetwork) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DKGNetwork) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *DKGNetwork) GetStage() DKGStage {
	if m != nil {
		return m.Stage
	}
	return DKGStageUnspecified
}

type DKGRegistration struct {
	Mrenclave  []byte       `protobuf:"bytes,1,opt,name=mrenclave,proto3" json:"mrenclave,omitempty" yaml:"mrenclave"`
	Round      uint32       `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty" yaml:"round"`
	MsgSender  string       `protobuf:"bytes,3,opt,name=msg_sender,json=msgSender,proto3" json:"msg_sender,omitempty" yaml:"msg_sender"`
	Index      uint32       `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty" yaml:"index"`
	DkgPubKey  []byte       `protobuf:"bytes,5,opt,name=dkg_pub_key,json=dkgPubKey,proto3" json:"dkg_pub_key,omitempty" yaml:"dkg_pub_key"`
	CommPubKey []byte       `protobuf:"bytes,6,opt,name=comm_pub_key,json=commPubKey,proto3" json:"comm_pub_key,omitempty" yaml:"comm_pub_key"`
	RawQuote   []byte       `protobuf:"bytes,7,opt,name=raw_quote,json=rawQuote,proto3" json:"raw_quote,omitempty" yaml:"raw_quote"`
	Status     DKGRegStatus `protobuf:"varint,8,opt,name=status,proto3,enum=story.dkg.v1.types.DKGRegStatus" json:"status,omitempty" yaml:"status"`
}

func (m *DKGRegistration) Reset()         { *m = DKGRegistration{} }
func (m *DKGRegistration) String() string { return proto.CompactTextString(m) }
func (*DKGRegistration) ProtoMessage()    {}
func (*DKGRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{1}
}
func (m *DKGRegistration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DKGRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DKGRegistration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DKGRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGRegistration.Merge(m, src)
}
func (m *DKGRegistration) XXX_Size() int {
	return m.Size()
}
func (m *DKGRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_DKGRegistration proto.InternalMessageInfo

func (m *DKGRegistration) GetMrenclave() []byte {
	if m != nil {
		return m.Mrenclave
	}
	return nil
}

func (m *DKGRegistration) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *DKGRegistration) GetMsgSender() string {
	if m != nil {
		return m.MsgSender
	}
	return ""
}

func (m *DKGRegistration) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DKGRegistration) GetDkgPubKey() []byte {
	if m != nil {
		return m.DkgPubKey
	}
	return nil
}

func (m *DKGRegistration) GetCommPubKey() []byte {
	if m != nil {
		return m.CommPubKey
	}
	return nil
}

func (m *DKGRegistration) GetRawQuote() []byte {
	if m != nil {
		return m.RawQuote
	}
	return nil
}

func (m *DKGRegistration) GetStatus() DKGRegStatus {
	if m != nil {
		return m.Status
	}
	return DKGRegStatusUnspecified
}

type TEEUpgradeInfo struct {
	Mrenclave        []byte `protobuf:"bytes,1,opt,name=mrenclave,proto3" json:"mrenclave,omitempty" yaml:"mrenclave"`
	ActivationHeight int64  `protobuf:"varint,2,opt,name=activation_height,json=activationHeight,proto3" json:"activation_height,omitempty" yaml:"activation_height"`
}

func (m *TEEUpgradeInfo) Reset()         { *m = TEEUpgradeInfo{} }
func (m *TEEUpgradeInfo) String() string { return proto.CompactTextString(m) }
func (*TEEUpgradeInfo) ProtoMessage()    {}
func (*TEEUpgradeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{2}
}
func (m *TEEUpgradeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TEEUpgradeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TEEUpgradeInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TEEUpgradeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TEEUpgradeInfo.Merge(m, src)
}
func (m *TEEUpgradeInfo) XXX_Size() int {
	return m.Size()
}
func (m *TEEUpgradeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TEEUpgradeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TEEUpgradeInfo proto.InternalMessageInfo

func (m *TEEUpgradeInfo) GetMrenclave() []byte {
	if m != nil {
		return m.Mrenclave
	}
	return nil
}

func (m *TEEUpgradeInfo) GetActivationHeight() int64 {
	if m != nil {
		return m.ActivationHeight
	}
	return 0
}

type EncryptedDeal struct {
	DhKey     []byte `protobuf:"bytes,1,opt,name=dh_key,json=dhKey,proto3" json:"dh_key,omitempty" yaml:"dh_key"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" yaml:"signature"`
	Nonce     []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty" yaml:"nonce"`
	Cipher    []byte `protobuf:"bytes,4,opt,name=cipher,proto3" json:"cipher,omitempty" yaml:"cipher"`
}

func (m *EncryptedDeal) Reset()         { *m = EncryptedDeal{} }
func (m *EncryptedDeal) String() string { return proto.CompactTextString(m) }
func (*EncryptedDeal) ProtoMessage()    {}
func (*EncryptedDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{3}
}
func (m *EncryptedDeal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EncryptedDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EncryptedDeal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EncryptedDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedDeal.Merge(m, src)
}
func (m *EncryptedDeal) XXX_Size() int {
	return m.Size()
}
func (m *EncryptedDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedDeal.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedDeal proto.InternalMessageInfo

func (m *EncryptedDeal) GetDhKey() []byte {
	if m != nil {
		return m.DhKey
	}
	return nil
}

func (m *EncryptedDeal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *EncryptedDeal) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *EncryptedDeal) GetCipher() []byte {
	if m != nil {
		return m.Cipher
	}
	return nil
}

type Deal struct {
	Index          uint32        `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty" yaml:"index"`
	RecipientIndex uint32        `protobuf:"varint,2,opt,name=recipient_index,json=recipientIndex,proto3" json:"recipient_index,omitempty" yaml:"recipient_index"`
	Deal           EncryptedDeal `protobuf:"bytes,3,opt,name=deal,proto3" json:"deal" yaml:"deal"`
	Signature      []byte        `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty" yaml:"signature"`
}

func (m *Deal) Reset()         { *m = Deal{} }
func (m *Deal) String() string { return proto.CompactTextString(m) }
func (*Deal) ProtoMessage()    {}
func (*Deal) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{4}
}
func (m *Deal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Deal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Deal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Deal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deal.Merge(m, src)
}
func (m *Deal) XXX_Size() int {
	return m.Size()
}
func (m *Deal) XXX_DiscardUnknown() {
	xxx_messageInfo_Deal.DiscardUnknown(m)
}

var xxx_messageInfo_Deal proto.InternalMessageInfo

func (m *Deal) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Deal) GetRecipientIndex() uint32 {
	if m != nil {
		return m.RecipientIndex
	}
	return 0
}

func (m *Deal) GetDeal() EncryptedDeal {
	if m != nil {
		return m.Deal
	}
	return EncryptedDeal{}
}

func (m *Deal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Complaint struct {
	DealerIndex uint32 `protobuf:"varint,1,opt,name=dealer_index,json=dealerIndex,proto3" json:"dealer_index,omitempty" yaml:"dealer_index"`
	Signature   []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" yaml:"signature"`
}

func (m *Complaint) Reset()         { *m = Complaint{} }
func (m *Complaint) String() string { return proto.CompactTextString(m) }
func (*Complaint) ProtoMessage()    {}
func (*Complaint) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{5}
}
func (m *Complaint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Complaint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Complaint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Complaint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Complaint.Merge(m, src)
}
func (m *Complaint) XXX_Size() int {
	return m.Size()
}
func (m *Complaint) XXX_DiscardUnknown() {
	xxx_messageInfo_Complaint.DiscardUnknown(m)
}

var xxx_messageInfo_Complaint proto.InternalMessageInfo

func (m *Complaint) GetDealerIndex() uint32 {
	if m != nil {
		return m.DealerIndex
	}
	return 0
}

func (m *Complaint) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Response struct {
	Index       uint32       `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	VssResponse *VSSResponse `protobuf:"bytes,2,opt,name=vss_response,proto3" json:"vss_response,omitempty"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{6}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Response.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return m.Size()
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Response) GetVssResponse() *VSSResponse {
	if m != nil {
		return m.VssResponse
	}
	return nil
}

type VSSResponse struct {
	SessionId []byte `protobuf:"bytes,1,opt,name=session_id,proto3" json:"session_id,omitempty"`
	Index     uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Status    bool   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *VSSResponse) Reset()         { *m = VSSResponse{} }
func (m *VSSResponse) String() string { return proto.CompactTextString(m) }
func (*VSSResponse) ProtoMessage()    {}
func (*VSSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{7}
}
func (m *VSSResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VSSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VSSResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VSSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VSSResponse.Merge(m, src)
}
func (m *VSSResponse) XXX_Size() int {
	return m.Size()
}
func (m *VSSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VSSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VSSResponse proto.InternalMessageInfo

func (m *VSSResponse) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *VSSResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *VSSResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *VSSResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("story.dkg.v1.types.DKGRegStatus", DKGRegStatus_name, DKGRegStatus_value)
	proto.RegisterEnum("story.dkg.v1.types.DKGStage", DKGStage_name, DKGStage_value)
	proto.RegisterType((*DKGNetwork)(nil), "story.dkg.v1.types.DKGNetwork")
	proto.RegisterType((*DKGRegistration)(nil), "story.dkg.v1.types.DKGRegistration")
	proto.RegisterType((*TEEUpgradeInfo)(nil), "story.dkg.v1.types.TEEUpgradeInfo")
	proto.RegisterType((*EncryptedDeal)(nil), "story.dkg.v1.types.EncryptedDeal")
	proto.RegisterType((*Deal)(nil), "story.dkg.v1.types.Deal")
	proto.RegisterType((*Complaint)(nil), "story.dkg.v1.types.Complaint")
	proto.RegisterType((*Response)(nil), "story.dkg.v1.types.Response")
	proto.RegisterType((*VSSResponse)(nil), "story.dkg.v1.types.VSSResponse")
}

func init() { proto.RegisterFile("story/dkg/v1/types/types.proto", fileDescriptor_a7c6c6d7f465ec7b) }

var fileDescriptor_a7c6c6d7f465ec7b = []byte{
	// 1187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcf, 0x8f, 0xda, 0x46,
	0x14, 0x5e, 0x2f, 0x2c, 0x5d, 0x06, 0xb2, 0x61, 0xbd, 0x1b, 0xd6, 0x71, 0x22, 0xec, 0xce, 0xa1,
	0xa2, 0xa9, 0x04, 0x5a, 0x9a, 0x36, 0x6a, 0x7a, 0xa8, 0x60, 0x71, 0x28, 0x25, 0x25, 0xe9, 0xc0,
	0x6e, 0xa5, 0x5c, 0x2c, 0x83, 0x27, 0xc6, 0xc2, 0xd8, 0xae, 0x3d, 0x90, 0xd0, 0x5e, 0x7b, 0xa8,
	0xb8, 0xb4, 0xff, 0x00, 0xa7, 0xfe, 0x1f, 0x55, 0x8f, 0x39, 0xe6, 0xd8, 0x13, 0xaa, 0x92, 0xff,
	0x80, 0x9e, 0xab, 0x56, 0x9e, 0xe1, 0xc7, 0x78, 0x37, 0xad, 0xaa, 0x48, 0xbd, 0x20, 0xfb, 0x7d,
	0xdf, 0xf7, 0x3c, 0xef, 0x7b, 0xef, 0x61, 0x83, 0x42, 0x48, 0xbc, 0x60, 0x5a, 0x36, 0x87, 0x56,
	0x79, 0x72, 0x5a, 0x26, 0x53, 0x1f, 0x87, 0xec, 0xb7, 0xe4, 0x07, 0x1e, 0xf1, 0x44, 0x91, 0xe2,
	0x25, 0x73, 0x68, 0x95, 0x26, 0xa7, 0x25, 0x8a, 0xc8, 0xc7, 0x96, 0x67, 0x79, 0x14, 0x2e, 0x47,
	0x57, 0x8c, 0x09, 0xbf, 0x4f, 0x00, 0x50, 0x6f, 0x35, 0xda, 0x98, 0x3c, 0xf3, 0x82, 0xa1, 0x58,
	0x01, 0xe9, 0x51, 0x80, 0xdd, 0xbe, 0x63, 0x4c, 0xb0, 0x24, 0xa8, 0x42, 0x31, 0x5b, 0x3b, 0x5e,
	0x2e, 0x94, 0xdc, 0xd4, 0x18, 0x39, 0xf7, 0xe1, 0x06, 0x82, 0x68, 0x4b, 0x13, 0xdf, 0x03, 0x7b,
	0x81, 0x37, 0x76, 0x4d, 0x69, 0x57, 0x15, 0x8a, 0xd7, 0x6a, 0xb9, 0xe5, 0x42, 0xc9, 0x32, 0x3e,
	0x0d, 0x43, 0xc4, 0x60, 0xf1, 0x1e, 0xc8, 0x84, 0xc4, 0x08, 0x88, 0xde, 0x73, 0xbc, 0xfe, 0x50,
	0x4a, 0xa8, 0x42, 0x31, 0x51, 0xcb, 0x2f, 0x17, 0x8a, 0xc8, 0xd8, 0x1c, 0x08, 0x11, 0xa0, 0x77,
	0xb5, 0xe8, 0x46, 0xfc, 0x0c, 0x1c, 0x18, 0x7d, 0x62, 0x4f, 0xb0, 0x3e, 0x31, 0x1c, 0x3d, 0xc4,
	0x44, 0x4a, 0xaa, 0x89, 0x62, 0xba, 0x76, 0x73, 0xb9, 0x50, 0x6e, 0x30, 0x6d, 0x1c, 0x87, 0x28,
	0xcb, 0x02, 0x17, 0x86, 0xd3, 0xc1, 0x24, 0x3a, 0x21, 0xf1, 0x88, 0xe1, 0x48, 0x7b, 0x97, 0x4f,
	0x48, 0xc3, 0x10, 0x31, 0x38, 0xaa, 0x9e, 0x0c, 0x02, 0x1c, 0x0e, 0x3c, 0xc7, 0x94, 0x52, 0x94,
	0xcb, 0x55, 0xbf, 0x81, 0x20, 0xda, 0xd2, 0xc4, 0x3a, 0xd8, 0x0b, 0x89, 0x61, 0x61, 0xe9, 0x1d,
	0x55, 0x28, 0x1e, 0x54, 0x6e, 0x97, 0xae, 0x5a, 0x5f, 0xaa, 0xb7, 0x1a, 0x9d, 0x88, 0xc3, 0x3f,
	0x99, 0x8a, 0x20, 0x62, 0x62, 0xf8, 0x4b, 0x02, 0x5c, 0xaf, 0xb7, 0x1a, 0x08, 0x5b, 0x76, 0x48,
	0x02, 0x83, 0xd8, 0x9e, 0xfb, 0xbf, 0xf6, 0xe2, 0x2e, 0x00, 0xa3, 0xd0, 0xd2, 0x43, 0xec, 0x9a,
	0x38, 0xa0, 0xad, 0x48, 0xd7, 0x6e, 0x2c, 0x17, 0xca, 0xe1, 0x2a, 0xf9, 0x06, 0x8b, 0xb2, 0x87,
	0x56, 0x87, 0x5e, 0x47, 0xd9, 0x6d, 0xd7, 0xc4, 0xcf, 0xa5, 0xe4, 0xe5, 0xec, 0x34, 0x0c, 0x11,
	0x83, 0xc5, 0x8f, 0x41, 0xc6, 0x1c, 0x5a, 0xba, 0x3f, 0xee, 0xe9, 0x43, 0x3c, 0xa5, 0xae, 0x67,
	0xf9, 0x4e, 0x73, 0x20, 0x44, 0x69, 0x73, 0x68, 0x3d, 0x1e, 0xf7, 0x5a, 0x78, 0x2a, 0x7e, 0x02,
	0xb2, 0x7d, 0x6f, 0x34, 0xda, 0x08, 0x53, 0x54, 0x78, 0xb2, 0x5c, 0x28, 0x47, 0x4c, 0xc8, 0xa3,
	0x10, 0x81, 0xe8, 0x76, 0x25, 0x3d, 0x05, 0xe9, 0xc0, 0x78, 0xa6, 0x7f, 0x33, 0xf6, 0x08, 0x6b,
	0x45, 0xcc, 0xac, 0x0d, 0x04, 0xd1, 0x7e, 0x60, 0x3c, 0xfb, 0x2a, 0xba, 0x14, 0x5b, 0x20, 0x15,
	0x12, 0x83, 0x8c, 0x43, 0x69, 0x9f, 0xb6, 0x4e, 0xfd, 0x87, 0xd6, 0x21, 0x6c, 0x75, 0x28, 0xaf,
	0x76, 0xb8, 0x5c, 0x28, 0xd7, 0x36, 0xed, 0x23, 0xe3, 0x10, 0xa2, 0x55, 0x0a, 0xf8, 0xa3, 0x00,
	0x0e, 0xba, 0x9a, 0x76, 0xee, 0x5b, 0x81, 0x61, 0xe2, 0xa6, 0xfb, 0xd4, 0x7b, 0xab, 0xfe, 0x35,
	0xc1, 0x21, 0x9d, 0x5c, 0x3a, 0x01, 0xfa, 0x00, 0xdb, 0xd6, 0x80, 0xd0, 0x5e, 0x26, 0x6a, 0xb7,
	0x97, 0x0b, 0x45, 0xe2, 0xa6, 0x9d, 0xa7, 0x40, 0x94, 0xdb, 0xc6, 0x3e, 0x67, 0xa1, 0x5f, 0x05,
	0x70, 0x4d, 0x73, 0xfb, 0xc1, 0xd4, 0x27, 0xd8, 0xac, 0x63, 0xc3, 0x11, 0x8b, 0x20, 0x65, 0x0e,
	0xa8, 0xb1, 0xec, 0x34, 0x5c, 0x39, 0x2c, 0x0e, 0xd1, 0x9e, 0x39, 0x88, 0xdc, 0xac, 0x80, 0x74,
	0x68, 0x5b, 0xae, 0x41, 0xc6, 0x01, 0xa6, 0x8f, 0x8f, 0x1d, 0x7d, 0x03, 0x41, 0xb4, 0xa5, 0x45,
	0xc3, 0xe1, 0x7a, 0x6e, 0x1f, 0xd3, 0x69, 0xca, 0xf2, 0xc3, 0x41, 0xc3, 0x10, 0x31, 0x58, 0x7c,
	0x1f, 0xa4, 0xfa, 0xb6, 0x3f, 0xc0, 0x01, 0x9d, 0xa2, 0xd8, 0x29, 0x58, 0x1c, 0xa2, 0x15, 0x01,
	0xfe, 0x21, 0x80, 0x24, 0x3d, 0xf9, 0x66, 0xf0, 0x84, 0x7f, 0x1f, 0xbc, 0x33, 0x70, 0x3d, 0xc0,
	0x7d, 0xdb, 0xb7, 0xb1, 0x4b, 0x74, 0xa6, 0x60, 0x8b, 0x20, 0x2f, 0x17, 0x4a, 0x7e, 0x35, 0x0b,
	0x71, 0x02, 0x44, 0x07, 0x9b, 0x48, 0x93, 0x26, 0xf9, 0x02, 0x24, 0x4d, 0x6c, 0x38, 0xb4, 0x8e,
	0x4c, 0xe5, 0xdd, 0x37, 0x4d, 0x45, 0xcc, 0xd7, 0xda, 0xd1, 0x8b, 0x85, 0xb2, 0xb3, 0x5c, 0x28,
	0x99, 0x95, 0x97, 0x38, 0xfa, 0x4b, 0xa1, 0x39, 0xe2, 0x46, 0x26, 0xff, 0x93, 0x91, 0xf0, 0x3b,
	0x90, 0x3e, 0xf3, 0x46, 0xbe, 0x63, 0xd8, 0x2e, 0x11, 0xef, 0x83, 0x6c, 0x94, 0x08, 0x07, 0x3a,
	0x6f, 0x00, 0xb7, 0x12, 0x3c, 0x0a, 0x51, 0x86, 0xdd, 0xb2, 0x42, 0xde, 0xa2, 0x8b, 0x10, 0x83,
	0x7d, 0x84, 0x43, 0xdf, 0x73, 0x43, 0x2c, 0x1e, 0xc7, 0x5c, 0xdf, 0x7a, 0x9c, 0x9d, 0x84, 0xa1,
	0x1e, 0xac, 0x58, 0x34, 0x71, 0xa6, 0xa2, 0xbc, 0xc9, 0xa6, 0x8b, 0x4e, 0x67, 0x9d, 0x0c, 0xc5,
	0x44, 0x70, 0x0a, 0x32, 0x1c, 0x28, 0x16, 0x00, 0x08, 0x71, 0x18, 0x46, 0x03, 0x6d, 0x9b, 0x6c,
	0x3a, 0x11, 0x17, 0xd9, 0x9e, 0x64, 0x97, 0x3f, 0x49, 0x7e, 0xb3, 0xc0, 0x51, 0xab, 0xf6, 0xd7,
	0xbb, 0x28, 0xde, 0xbe, 0x62, 0x3a, 0x57, 0xe1, 0x9d, 0x3f, 0x05, 0x90, 0xe5, 0xb7, 0x5a, 0xfc,
	0x14, 0xc8, 0xf5, 0x56, 0x43, 0x47, 0x5a, 0x43, 0xef, 0x74, 0xab, 0xdd, 0xf3, 0x8e, 0x7e, 0xde,
	0xee, 0x3c, 0xd6, 0xce, 0x9a, 0x0f, 0x9a, 0x5a, 0x3d, 0xb7, 0x23, 0xdf, 0x9a, 0xcd, 0xd5, 0x13,
	0x5e, 0x71, 0xee, 0x86, 0x3e, 0xee, 0xdb, 0x4f, 0x6d, 0x6c, 0x8a, 0x1f, 0x81, 0x93, 0x4b, 0xe2,
	0x0b, 0x0d, 0x31, 0xe5, 0xae, 0x2c, 0xcd, 0xe6, 0xea, 0x31, 0xaf, 0xbc, 0xc0, 0x01, 0x93, 0xdd,
	0xbf, 0xf2, 0xcc, 0xb6, 0xd6, 0xfd, 0xfa, 0x11, 0x6a, 0xe9, 0x1d, 0xad, 0x9b, 0x4b, 0xc8, 0xf2,
	0x6c, 0xae, 0xe6, 0x79, 0xe5, 0xea, 0x05, 0x1d, 0xbd, 0xcd, 0xee, 0x01, 0xe9, 0x92, 0xf6, 0x41,
	0xb3, 0x5d, 0x7d, 0xd8, 0x7c, 0xa2, 0xd5, 0x73, 0x49, 0xf9, 0xe6, 0x6c, 0xae, 0xde, 0xe0, 0x95,
	0x0f, 0x6c, 0xd7, 0x70, 0xec, 0x6f, 0xb1, 0x29, 0x27, 0x7f, 0xf8, 0xb9, 0xb0, 0x73, 0xe7, 0xaf,
	0x5d, 0xb0, 0xbf, 0x7e, 0x21, 0x89, 0x15, 0x10, 0x71, 0xa3, 0x3c, 0x0d, 0xed, 0x52, 0xd9, 0x27,
	0xb3, 0xb9, 0x7a, 0xb4, 0x26, 0xf2, 0x25, 0xdf, 0x05, 0xf9, 0xad, 0x06, 0x69, 0x8d, 0x66, 0xa7,
	0x8b, 0xaa, 0xdd, 0xe6, 0xa3, 0x76, 0x4e, 0xd8, 0x54, 0x4c, 0x45, 0xb1, 0xb7, 0xd9, 0x29, 0xff,
	0x24, 0xbe, 0xd8, 0x5d, 0x39, 0x3f, 0x9b, 0xab, 0xe2, 0x5a, 0xc4, 0x15, 0x5a, 0x07, 0xca, 0x1b,
	0x25, 0xfa, 0xd9, 0xa3, 0x2f, 0x1f, 0x3f, 0xd4, 0xba, 0x5a, 0x3d, 0x97, 0x90, 0x95, 0xd9, 0x5c,
	0xbd, 0x75, 0x55, 0x4c, 0x37, 0x08, 0x13, 0x6c, 0x8a, 0x77, 0xc0, 0xe1, 0x36, 0x4b, 0x5d, 0xab,
	0x3e, 0x6c, 0xb6, 0x1b, 0xb9, 0xa4, 0x7c, 0x34, 0x9b, 0xab, 0xd7, 0xd7, 0xba, 0x68, 0x8d, 0x6d,
	0xd7, 0x8a, 0x97, 0xb6, 0x72, 0x95, 0x95, 0xb6, 0x17, 0x2f, 0x6d, 0x65, 0x2a, 0x2b, 0xad, 0x08,
	0x72, 0x5b, 0x55, 0xf5, 0xac, 0xdb, 0xbc, 0xd0, 0x72, 0x29, 0x59, 0x9c, 0xcd, 0xd5, 0x83, 0x35,
	0xbf, 0x4a, 0x3f, 0x47, 0x58, 0x07, 0x6a, 0xda, 0x8b, 0x57, 0x05, 0xe1, 0xe5, 0xab, 0x82, 0xf0,
	0xfb, 0xab, 0x82, 0xf0, 0xd3, 0xeb, 0xc2, 0xce, 0xcb, 0xd7, 0x85, 0x9d, 0xdf, 0x5e, 0x17, 0x76,
	0x9e, 0x7c, 0x60, 0xd9, 0x64, 0x30, 0xee, 0x95, 0xfa, 0xde, 0xa8, 0xec, 0xdb, 0xbe, 0x63, 0xf4,
	0xc2, 0x32, 0xfb, 0xd4, 0xeb, 0x3b, 0xd1, 0x1f, 0x54, 0xf9, 0x39, 0xfd, 0xe6, 0xa3, 0xdb, 0xd5,
	0x4b, 0xd1, 0x2f, 0xb8, 0x0f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x6f, 0x57, 0xb0, 0x0d,
	0x0a, 0x00, 0x00,
}

func (m *DKGNetwork) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DKGNetwork) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DKGNetwork) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Stage != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Stage))
		i--
		dAtA[i] = 0x38
	}
	if m.Threshold != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Threshold))
		i--
		dAtA[i] = 0x30
	}
	if m.Total != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ActiveValSet) > 0 {
		for iNdEx := len(m.ActiveValSet) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ActiveValSet[iNdEx])
			copy(dAtA[i:], m.ActiveValSet[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.ActiveValSet[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.StartBlock != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.StartBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.Round != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DKGRegistration) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DKGRegistration) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DKGRegistration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x40
	}
	if len(m.RawQuote) > 0 {
		i -= len(m.RawQuote)
		copy(dAtA[i:], m.RawQuote)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RawQuote)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CommPubKey) > 0 {
		i -= len(m.CommPubKey)
		copy(dAtA[i:], m.CommPubKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CommPubKey)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DkgPubKey) > 0 {
		i -= len(m.DkgPubKey)
		copy(dAtA[i:], m.DkgPubKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DkgPubKey)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Index != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x20
	}
	if len(m.MsgSender) > 0 {
		i -= len(m.MsgSender)
		copy(dAtA[i:], m.MsgSender)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MsgSender)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Round != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TEEUpgradeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TEEUpgradeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TEEUpgradeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActivationHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ActivationHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EncryptedDeal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EncryptedDeal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EncryptedDeal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Cipher) > 0 {
		i -= len(m.Cipher)
		copy(dAtA[i:], m.Cipher)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Cipher)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DhKey) > 0 {
		i -= len(m.DhKey)
		copy(dAtA[i:], m.DhKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DhKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Deal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Deal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Deal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Deal.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.RecipientIndex != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RecipientIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.Index != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Complaint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Complaint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Complaint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if m.DealerIndex != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.DealerIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Response) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VssResponse != nil {
		{
			size, err := m.VssResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VSSResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VSSResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VSSResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x22
	}
	if m.Status {
		i--
		if m.Status {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Index != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SessionId) > 0 {
		i -= len(m.SessionId)
		copy(dAtA[i:], m.SessionId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SessionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DKGNetwork) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovTypes(uint64(m.Round))
	}
	if m.StartBlock != 0 {
		n += 1 + sovTypes(uint64(m.StartBlock))
	}
	if len(m.ActiveValSet) > 0 {
		for _, s := range m.ActiveValSet {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Total != 0 {
		n += 1 + sovTypes(uint64(m.Total))
	}
	if m.Threshold != 0 {
		n += 1 + sovTypes(uint64(m.Threshold))
	}
	if m.Stage != 0 {
		n += 1 + sovTypes(uint64(m.Stage))
	}
	return n
}

func (m *DKGRegistration) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovTypes(uint64(m.Round))
	}
	l = len(m.MsgSender)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovTypes(uint64(m.Index))
	}
	l = len(m.DkgPubKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CommPubKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.RawQuote)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	return n
}

func (m *TEEUpgradeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ActivationHeight != 0 {
		n += 1 + sovTypes(uint64(m.ActivationHeight))
	}
	return n
}

func (m *EncryptedDeal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DhKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Cipher)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Deal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovTypes(uint64(m.Index))
	}
	if m.RecipientIndex != 0 {
		n += 1 + sovTypes(uint64(m.RecipientIndex))
	}
	l = m.Deal.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Complaint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DealerIndex != 0 {
		n += 1 + sovTypes(uint64(m.DealerIndex))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Response) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovTypes(uint64(m.Index))
	}
	if m.VssResponse != nil {
		l = m.VssResponse.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *VSSResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SessionId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovTypes(uint64(m.Index))
	}
	if m.Status {
		n += 2
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DKGNetwork) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DKGNetwork: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DKGNetwork: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = append(m.Mrenclave[:0], dAtA[iNdEx:postIndex]...)
			if m.Mrenclave == nil {
				m.Mrenclave = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlock", wireType)
			}
			m.StartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveValSet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActiveValSet = append(m.ActiveValSet, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threshold", wireType)
			}
			m.Threshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Threshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stage", wireType)
			}
			m.Stage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stage |= DKGStage(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DKGRegistration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DKGRegistration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DKGRegistration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = append(m.Mrenclave[:0], dAtA[iNdEx:postIndex]...)
			if m.Mrenclave == nil {
				m.Mrenclave = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgSender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgSender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DkgPubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DkgPubKey = append(m.DkgPubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.DkgPubKey == nil {
				m.DkgPubKey = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommPubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommPubKey = append(m.CommPubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.CommPubKey == nil {
				m.CommPubKey = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawQuote", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawQuote = append(m.RawQuote[:0], dAtA[iNdEx:postIndex]...)
			if m.RawQuote == nil {
				m.RawQuote = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= DKGRegStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TEEUpgradeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TEEUpgradeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TEEUpgradeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = append(m.Mrenclave[:0], dAtA[iNdEx:postIndex]...)
			if m.Mrenclave == nil {
				m.Mrenclave = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationHeight", wireType)
			}
			m.ActivationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EncryptedDeal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EncryptedDeal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EncryptedDeal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DhKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DhKey = append(m.DhKey[:0], dAtA[iNdEx:postIndex]...)
			if m.DhKey == nil {
				m.DhKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = append(m.Nonce[:0], dAtA[iNdEx:postIndex]...)
			if m.Nonce == nil {
				m.Nonce = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cipher", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cipher = append(m.Cipher[:0], dAtA[iNdEx:postIndex]...)
			if m.Cipher == nil {
				m.Cipher = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Deal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Deal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Deal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientIndex", wireType)
			}
			m.RecipientIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecipientIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Deal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Complaint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Complaint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Complaint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealerIndex", wireType)
			}
			m.DealerIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DealerIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VssResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VssResponse == nil {
				m.VssResponse = &VSSResponse{}
			}
			if err := m.VssResponse.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VSSResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VSSResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VSSResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionId = append(m.SessionId[:0], dAtA[iNdEx:postIndex]...)
			if m.SessionId == nil {
				m.SessionId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Status = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
