// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: story/dkg/v1/types/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DKGRegStatus int32

const (
	DKGRegStatusUnspecified DKGRegStatus = 0
	DKGRegStatusVerified    DKGRegStatus = 1
	DKGRegStatusFinalized   DKGRegStatus = 2
	DKGRegStatusInvalidated DKGRegStatus = 3
)

var DKGRegStatus_name = map[int32]string{
	0: "DKG_REG_STATUS_UNSPECIFIED",
	1: "DKG_REG_STATUS_VERIFIED",
	2: "DKG_REG_STATUS_FINALIZED",
	3: "DKG_REG_STATUS_INVALIDATED",
}

var DKGRegStatus_value = map[string]int32{
	"DKG_REG_STATUS_UNSPECIFIED": 0,
	"DKG_REG_STATUS_VERIFIED":    1,
	"DKG_REG_STATUS_FINALIZED":   2,
	"DKG_REG_STATUS_INVALIDATED": 3,
}

func (x DKGRegStatus) String() string {
	return proto.EnumName(DKGRegStatus_name, int32(x))
}

func (DKGRegStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{0}
}

type DKGStage int32

const (
	DKGStageUnspecified  DKGStage = 0
	DKGStageRegistration DKGStage = 1
	DKGStageDealing      DKGStage = 2
	DKGStageFinalization DKGStage = 3
	DKGStageActive       DKGStage = 4
	DKGStageFailed       DKGStage = 5
)

var DKGStage_name = map[int32]string{
	0: "DKG_STAGE_UNSPECIFIED",
	1: "DKG_STAGE_REGISTRATION",
	2: "DKG_STAGE_DEALING",
	3: "DKG_STAGE_FINALIZATION",
	4: "DKG_STAGE_ACTIVE",
	5: "DKG_STAGE_FAILED",
}

var DKGStage_value = map[string]int32{
	"DKG_STAGE_UNSPECIFIED":  0,
	"DKG_STAGE_REGISTRATION": 1,
	"DKG_STAGE_DEALING":      2,
	"DKG_STAGE_FINALIZATION": 3,
	"DKG_STAGE_ACTIVE":       4,
	"DKG_STAGE_FAILED":       5,
}

func (x DKGStage) String() string {
	return proto.EnumName(DKGStage_name, int32(x))
}

func (DKGStage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{1}
}

type DKGNetwork struct {
	CodeCommitment   []byte `protobuf:"bytes,1,opt,name=code_commitment,json=codeCommitment,proto3" json:"code_commitment,omitempty" yaml:"code_commitment"`
	Round            uint32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty" yaml:"round"`
	StartBlockHeight int64  `protobuf:"varint,3,opt,name=start_block_height,json=startBlockHeight,proto3" json:"start_block_height,omitempty" yaml:"start_block_height"`
	StartBlockHash   []byte `protobuf:"bytes,4,opt,name=start_block_hash,json=startBlockHash,proto3" json:"start_block_hash,omitempty" yaml:"start_block_hash"`
	// list of active validators' evm addresses
	ActiveValSet    []string `protobuf:"bytes,5,rep,name=active_val_set,json=activeValSet,proto3" json:"active_val_set,omitempty" yaml:"active_val_set"`
	Total           uint32   `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty" yaml:"total"`
	Threshold       uint32   `protobuf:"varint,7,opt,name=threshold,proto3" json:"threshold,omitempty" yaml:"threshold"`
	Stage           DKGStage `protobuf:"varint,8,opt,name=stage,proto3,enum=story.dkg.v1.types.DKGStage" json:"stage,omitempty" yaml:"stage"`
	IsResharing     bool     `protobuf:"varint,9,opt,name=is_resharing,json=isResharing,proto3" json:"is_resharing,omitempty" yaml:"is_resharing"`
	GlobalPublicKey []byte   `protobuf:"bytes,10,opt,name=global_public_key,json=globalPublicKey,proto3" json:"global_public_key,omitempty" yaml:"global_public_key"`
	PublicCoeffs    [][]byte `protobuf:"bytes,11,rep,name=public_coeffs,json=publicCoeffs,proto3" json:"public_coeffs,omitempty" yaml:"public_coeffs"`
}

func (m *DKGNetwork) Reset()         { *m = DKGNetwork{} }
func (m *DKGNetwork) String() string { return proto.CompactTextString(m) }
func (*DKGNetwork) ProtoMessage()    {}
func (*DKGNetwork) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{0}
}
func (m *DKGNetwork) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DKGNetwork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DKGNetwork.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DKGNetwork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGNetwork.Merge(m, src)
}
func (m *DKGNetwork) XXX_Size() int {
	return m.Size()
}
func (m *DKGNetwork) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGNetwork.DiscardUnknown(m)
}

var xxx_messageInfo_DKGNetwork proto.InternalMessageInfo

func (m *DKGNetwork) GetCodeCommitment() []byte {
	if m != nil {
		return m.CodeCommitment
	}
	return nil
}

func (m *DKGNetwork) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *DKGNetwork) GetStartBlockHeight() int64 {
	if m != nil {
		return m.StartBlockHeight
	}
	return 0
}

func (m *DKGNetwork) GetStartBlockHash() []byte {
	if m != nil {
		return m.StartBlockHash
	}
	return nil
}

func (m *DKGNetwork) GetActiveValSet() []string {
	if m != nil {
		return m.ActiveValSet
	}
	return nil
}

func (m *DKGNetwork) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DKGNetwork) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *DKGNetwork) GetStage() DKGStage {
	if m != nil {
		return m.Stage
	}
	return DKGStageUnspecified
}

func (m *DKGNetwork) GetIsResharing() bool {
	if m != nil {
		return m.IsResharing
	}
	return false
}

func (m *DKGNetwork) GetGlobalPublicKey() []byte {
	if m != nil {
		return m.GlobalPublicKey
	}
	return nil
}

func (m *DKGNetwork) GetPublicCoeffs() [][]byte {
	if m != nil {
		return m.PublicCoeffs
	}
	return nil
}

type DKGRegistration struct {
	Round         uint32       `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty" yaml:"round"`
	ValidatorAddr string       `protobuf:"bytes,2,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty" yaml:"validator_addr"`
	Index         uint32       `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty" yaml:"index"`
	DkgPubKey     []byte       `protobuf:"bytes,4,opt,name=dkg_pub_key,json=dkgPubKey,proto3" json:"dkg_pub_key,omitempty" yaml:"dkg_pub_key"`
	CommPubKey    []byte       `protobuf:"bytes,5,opt,name=comm_pub_key,json=commPubKey,proto3" json:"comm_pub_key,omitempty" yaml:"comm_pub_key"`
	PubKeyShare   []byte       `protobuf:"bytes,6,opt,name=pub_key_share,json=pubKeyShare,proto3" json:"pub_key_share,omitempty" yaml:"pub_key_share"`
	EnclaveReport []byte       `protobuf:"bytes,7,opt,name=enclave_report,json=enclaveReport,proto3" json:"enclave_report,omitempty" yaml:"enclave_report"`
	Status        DKGRegStatus `protobuf:"varint,8,opt,name=status,proto3,enum=story.dkg.v1.types.DKGRegStatus" json:"status,omitempty" yaml:"status"`
}

func (m *DKGRegistration) Reset()         { *m = DKGRegistration{} }
func (m *DKGRegistration) String() string { return proto.CompactTextString(m) }
func (*DKGRegistration) ProtoMessage()    {}
func (*DKGRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{1}
}
func (m *DKGRegistration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DKGRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DKGRegistration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DKGRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGRegistration.Merge(m, src)
}
func (m *DKGRegistration) XXX_Size() int {
	return m.Size()
}
func (m *DKGRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_DKGRegistration proto.InternalMessageInfo

func (m *DKGRegistration) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *DKGRegistration) GetValidatorAddr() string {
	if m != nil {
		return m.ValidatorAddr
	}
	return ""
}

func (m *DKGRegistration) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DKGRegistration) GetDkgPubKey() []byte {
	if m != nil {
		return m.DkgPubKey
	}
	return nil
}

func (m *DKGRegistration) GetCommPubKey() []byte {
	if m != nil {
		return m.CommPubKey
	}
	return nil
}

func (m *DKGRegistration) GetPubKeyShare() []byte {
	if m != nil {
		return m.PubKeyShare
	}
	return nil
}

func (m *DKGRegistration) GetEnclaveReport() []byte {
	if m != nil {
		return m.EnclaveReport
	}
	return nil
}

func (m *DKGRegistration) GetStatus() DKGRegStatus {
	if m != nil {
		return m.Status
	}
	return DKGRegStatusUnspecified
}

type TEEUpgradeInfo struct {
	CodeCommitment   []byte `protobuf:"bytes,1,opt,name=code_commitment,json=codeCommitment,proto3" json:"code_commitment,omitempty" yaml:"code_commitment"`
	ActivationHeight int64  `protobuf:"varint,2,opt,name=activation_height,json=activationHeight,proto3" json:"activation_height,omitempty" yaml:"activation_height"`
}

func (m *TEEUpgradeInfo) Reset()         { *m = TEEUpgradeInfo{} }
func (m *TEEUpgradeInfo) String() string { return proto.CompactTextString(m) }
func (*TEEUpgradeInfo) ProtoMessage()    {}
func (*TEEUpgradeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{2}
}
func (m *TEEUpgradeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TEEUpgradeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TEEUpgradeInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TEEUpgradeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TEEUpgradeInfo.Merge(m, src)
}
func (m *TEEUpgradeInfo) XXX_Size() int {
	return m.Size()
}
func (m *TEEUpgradeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TEEUpgradeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TEEUpgradeInfo proto.InternalMessageInfo

func (m *TEEUpgradeInfo) GetCodeCommitment() []byte {
	if m != nil {
		return m.CodeCommitment
	}
	return nil
}

func (m *TEEUpgradeInfo) GetActivationHeight() int64 {
	if m != nil {
		return m.ActivationHeight
	}
	return 0
}

type EncryptedDeal struct {
	DhKey     []byte `protobuf:"bytes,1,opt,name=dh_key,json=dhKey,proto3" json:"dh_key,omitempty" yaml:"dh_key"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" yaml:"signature"`
	Nonce     []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty" yaml:"nonce"`
	Cipher    []byte `protobuf:"bytes,4,opt,name=cipher,proto3" json:"cipher,omitempty" yaml:"cipher"`
}

func (m *EncryptedDeal) Reset()         { *m = EncryptedDeal{} }
func (m *EncryptedDeal) String() string { return proto.CompactTextString(m) }
func (*EncryptedDeal) ProtoMessage()    {}
func (*EncryptedDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{3}
}
func (m *EncryptedDeal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EncryptedDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EncryptedDeal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EncryptedDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedDeal.Merge(m, src)
}
func (m *EncryptedDeal) XXX_Size() int {
	return m.Size()
}
func (m *EncryptedDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedDeal.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedDeal proto.InternalMessageInfo

func (m *EncryptedDeal) GetDhKey() []byte {
	if m != nil {
		return m.DhKey
	}
	return nil
}

func (m *EncryptedDeal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *EncryptedDeal) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *EncryptedDeal) GetCipher() []byte {
	if m != nil {
		return m.Cipher
	}
	return nil
}

type Deal struct {
	Index          uint32        `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty" yaml:"index"`
	RecipientIndex uint32        `protobuf:"varint,2,opt,name=recipient_index,json=recipientIndex,proto3" json:"recipient_index,omitempty" yaml:"recipient_index"`
	Deal           EncryptedDeal `protobuf:"bytes,3,opt,name=deal,proto3" json:"deal" yaml:"deal"`
	Signature      []byte        `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty" yaml:"signature"`
}

func (m *Deal) Reset()         { *m = Deal{} }
func (m *Deal) String() string { return proto.CompactTextString(m) }
func (*Deal) ProtoMessage()    {}
func (*Deal) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{4}
}
func (m *Deal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Deal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Deal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Deal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deal.Merge(m, src)
}
func (m *Deal) XXX_Size() int {
	return m.Size()
}
func (m *Deal) XXX_DiscardUnknown() {
	xxx_messageInfo_Deal.DiscardUnknown(m)
}

var xxx_messageInfo_Deal proto.InternalMessageInfo

func (m *Deal) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Deal) GetRecipientIndex() uint32 {
	if m != nil {
		return m.RecipientIndex
	}
	return 0
}

func (m *Deal) GetDeal() EncryptedDeal {
	if m != nil {
		return m.Deal
	}
	return EncryptedDeal{}
}

func (m *Deal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Complaint struct {
	DealerIndex uint32 `protobuf:"varint,1,opt,name=dealer_index,json=dealerIndex,proto3" json:"dealer_index,omitempty" yaml:"dealer_index"`
	Signature   []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" yaml:"signature"`
}

func (m *Complaint) Reset()         { *m = Complaint{} }
func (m *Complaint) String() string { return proto.CompactTextString(m) }
func (*Complaint) ProtoMessage()    {}
func (*Complaint) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{5}
}
func (m *Complaint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Complaint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Complaint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Complaint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Complaint.Merge(m, src)
}
func (m *Complaint) XXX_Size() int {
	return m.Size()
}
func (m *Complaint) XXX_DiscardUnknown() {
	xxx_messageInfo_Complaint.DiscardUnknown(m)
}

var xxx_messageInfo_Complaint proto.InternalMessageInfo

func (m *Complaint) GetDealerIndex() uint32 {
	if m != nil {
		return m.DealerIndex
	}
	return 0
}

func (m *Complaint) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type DecryptRequest struct {
	Requester      string `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty" yaml:"requester"`
	Round          uint32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty" yaml:"round"`
	CodeCommitment []byte `protobuf:"bytes,3,opt,name=code_commitment,json=codeCommitment,proto3" json:"code_commitment,omitempty" yaml:"code_commitment"`
	Ciphertext     []byte `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty" yaml:"ciphertext"`
	Label          []byte `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty" yaml:"label"`
	// secp256k1 uncompressed requester pubkey (65 bytes)
	RequesterPubKey []byte `protobuf:"bytes,6,opt,name=requester_pub_key,json=requesterPubKey,proto3" json:"requester_pub_key,omitempty" yaml:"requester_pub_key"`
}

func (m *DecryptRequest) Reset()         { *m = DecryptRequest{} }
func (m *DecryptRequest) String() string { return proto.CompactTextString(m) }
func (*DecryptRequest) ProtoMessage()    {}
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{6}
}
func (m *DecryptRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DecryptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DecryptRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DecryptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptRequest.Merge(m, src)
}
func (m *DecryptRequest) XXX_Size() int {
	return m.Size()
}
func (m *DecryptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptRequest proto.InternalMessageInfo

func (m *DecryptRequest) GetRequester() string {
	if m != nil {
		return m.Requester
	}
	return ""
}

func (m *DecryptRequest) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *DecryptRequest) GetCodeCommitment() []byte {
	if m != nil {
		return m.CodeCommitment
	}
	return nil
}

func (m *DecryptRequest) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *DecryptRequest) GetLabel() []byte {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *DecryptRequest) GetRequesterPubKey() []byte {
	if m != nil {
		return m.RequesterPubKey
	}
	return nil
}

type Response struct {
	Index       uint32       `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty" yaml:"index"`
	VssResponse *VSSResponse `protobuf:"bytes,2,opt,name=vss_response,json=vssResponse,proto3" json:"vss_response,omitempty" yaml:"vss_response"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{7}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Response.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return m.Size()
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Response) GetVssResponse() *VSSResponse {
	if m != nil {
		return m.VssResponse
	}
	return nil
}

type VSSResponse struct {
	SessionId []byte `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty" yaml:"session_id"`
	Index     uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty" yaml:"index"`
	Status    bool   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty" yaml:"status"`
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty" yaml:"signature"`
}

func (m *VSSResponse) Reset()         { *m = VSSResponse{} }
func (m *VSSResponse) String() string { return proto.CompactTextString(m) }
func (*VSSResponse) ProtoMessage()    {}
func (*VSSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{8}
}
func (m *VSSResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VSSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VSSResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VSSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VSSResponse.Merge(m, src)
}
func (m *VSSResponse) XXX_Size() int {
	return m.Size()
}
func (m *VSSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VSSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VSSResponse proto.InternalMessageInfo

func (m *VSSResponse) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *VSSResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *VSSResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *VSSResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Scalar struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty" yaml:"data"`
}

func (m *Scalar) Reset()         { *m = Scalar{} }
func (m *Scalar) String() string { return proto.CompactTextString(m) }
func (*Scalar) ProtoMessage()    {}
func (*Scalar) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{9}
}
func (m *Scalar) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Scalar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Scalar.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Scalar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scalar.Merge(m, src)
}
func (m *Scalar) XXX_Size() int {
	return m.Size()
}
func (m *Scalar) XXX_DiscardUnknown() {
	xxx_messageInfo_Scalar.DiscardUnknown(m)
}

var xxx_messageInfo_Scalar proto.InternalMessageInfo

func (m *Scalar) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Point struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty" yaml:"data"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c6c6d7f465ec7b, []int{10}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Point.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return m.Size()
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("story.dkg.v1.types.DKGRegStatus", DKGRegStatus_name, DKGRegStatus_value)
	proto.RegisterEnum("story.dkg.v1.types.DKGStage", DKGStage_name, DKGStage_value)
	proto.RegisterType((*DKGNetwork)(nil), "story.dkg.v1.types.DKGNetwork")
	proto.RegisterType((*DKGRegistration)(nil), "story.dkg.v1.types.DKGRegistration")
	proto.RegisterType((*TEEUpgradeInfo)(nil), "story.dkg.v1.types.TEEUpgradeInfo")
	proto.RegisterType((*EncryptedDeal)(nil), "story.dkg.v1.types.EncryptedDeal")
	proto.RegisterType((*Deal)(nil), "story.dkg.v1.types.Deal")
	proto.RegisterType((*Complaint)(nil), "story.dkg.v1.types.Complaint")
	proto.RegisterType((*DecryptRequest)(nil), "story.dkg.v1.types.DecryptRequest")
	proto.RegisterType((*Response)(nil), "story.dkg.v1.types.Response")
	proto.RegisterType((*VSSResponse)(nil), "story.dkg.v1.types.VSSResponse")
	proto.RegisterType((*Scalar)(nil), "story.dkg.v1.types.Scalar")
	proto.RegisterType((*Point)(nil), "story.dkg.v1.types.Point")
}

func init() { proto.RegisterFile("story/dkg/v1/types/types.proto", fileDescriptor_a7c6c6d7f465ec7b) }

var fileDescriptor_a7c6c6d7f465ec7b = []byte{
	// 1458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x41, 0x6f, 0x1b, 0xc5,
	0x17, 0xcf, 0xc6, 0x71, 0xfe, 0xc9, 0xd8, 0x71, 0x9c, 0x4d, 0xda, 0x6c, 0xdd, 0xfe, 0xbd, 0x66,
	0x90, 0x90, 0x5b, 0x20, 0x51, 0x43, 0x0b, 0xa2, 0x80, 0xc0, 0x8e, 0x37, 0xee, 0x92, 0x28, 0x44,
	0xe3, 0x24, 0x87, 0x72, 0x58, 0x8d, 0x77, 0x27, 0xeb, 0x55, 0x36, 0xbb, 0x66, 0x77, 0x6c, 0x1a,
	0xf8, 0x02, 0x28, 0x17, 0xf8, 0x02, 0x91, 0x90, 0xf8, 0x02, 0x5c, 0xb8, 0x73, 0xac, 0x38, 0xf5,
	0x88, 0x38, 0x58, 0xa8, 0xf9, 0x06, 0xe6, 0x8e, 0xd0, 0xcc, 0xac, 0xed, 0xb1, 0x93, 0x56, 0xa1,
	0xe2, 0x92, 0x78, 0xde, 0xfb, 0xfd, 0xde, 0xcc, 0x7b, 0xf3, 0x9b, 0x37, 0xb3, 0xa0, 0x18, 0xd3,
	0x30, 0x3a, 0x5d, 0x77, 0x8e, 0xdd, 0xf5, 0xee, 0xfd, 0x75, 0x7a, 0xda, 0x26, 0xb1, 0xf8, 0xbb,
	0xd6, 0x8e, 0x42, 0x1a, 0xaa, 0x2a, 0xf7, 0xaf, 0x39, 0xc7, 0xee, 0x5a, 0xf7, 0xfe, 0x1a, 0xf7,
	0x14, 0x56, 0xdc, 0xd0, 0x0d, 0xb9, 0x7b, 0x9d, 0xfd, 0x12, 0x48, 0xf8, 0x4b, 0x1a, 0x80, 0xda,
	0x76, 0x7d, 0x97, 0xd0, 0xaf, 0xc3, 0xe8, 0x58, 0xdd, 0x04, 0x8b, 0x76, 0xe8, 0x10, 0xcb, 0x0e,
	0x4f, 0x4e, 0x3c, 0x7a, 0x42, 0x02, 0xaa, 0x29, 0x25, 0xa5, 0x9c, 0xad, 0x16, 0xfa, 0x3d, 0xfd,
	0xe6, 0x29, 0x3e, 0xf1, 0x1f, 0xc1, 0x09, 0x00, 0x44, 0x39, 0x66, 0xd9, 0x1c, 0x1a, 0xd4, 0xb7,
	0x40, 0x3a, 0x0a, 0x3b, 0x81, 0xa3, 0x4d, 0x97, 0x94, 0xf2, 0x42, 0x35, 0xdf, 0xef, 0xe9, 0x59,
	0x41, 0xe5, 0x66, 0x88, 0x84, 0x5b, 0xdd, 0x06, 0x6a, 0x4c, 0x71, 0x44, 0xad, 0xa6, 0x1f, 0xda,
	0xc7, 0x56, 0x8b, 0x78, 0x6e, 0x8b, 0x6a, 0xa9, 0x92, 0x52, 0x4e, 0x55, 0xff, 0xdf, 0xef, 0xe9,
	0xb7, 0x04, 0xe9, 0x32, 0x06, 0xa2, 0x3c, 0x37, 0x56, 0x99, 0xed, 0x31, 0x37, 0xa9, 0x06, 0xc8,
	0x8f, 0x01, 0x71, 0xdc, 0xd2, 0x66, 0xf8, 0xd2, 0x6f, 0xf7, 0x7b, 0xfa, 0xea, 0x15, 0xa1, 0x70,
	0xdc, 0x82, 0x28, 0x27, 0x05, 0xc2, 0x71, 0x4b, 0xfd, 0x14, 0xe4, 0xb0, 0x4d, 0xbd, 0x2e, 0xb1,
	0xba, 0xd8, 0xb7, 0x62, 0x42, 0xb5, 0x74, 0x29, 0x55, 0x9e, 0xaf, 0xde, 0xea, 0xf7, 0xf4, 0x1b,
	0x22, 0xc8, 0xb8, 0x1f, 0xa2, 0xac, 0x30, 0x1c, 0x62, 0xbf, 0x41, 0x78, 0xf2, 0x34, 0xa4, 0xd8,
	0xd7, 0x66, 0x27, 0x93, 0xe7, 0x66, 0x88, 0x84, 0x5b, 0xdd, 0x00, 0xf3, 0xb4, 0x15, 0x91, 0xb8,
	0x15, 0xfa, 0x8e, 0xf6, 0x3f, 0x8e, 0x5d, 0xe9, 0xf7, 0xf4, 0x7c, 0x82, 0x1d, 0xb8, 0x20, 0x1a,
	0xc1, 0xd4, 0x1a, 0x48, 0xc7, 0x14, 0xbb, 0x44, 0x9b, 0x2b, 0x29, 0xe5, 0xdc, 0xc6, 0x9d, 0xb5,
	0xcb, 0xdb, 0xbc, 0x56, 0xdb, 0xae, 0x37, 0x18, 0x46, 0x9e, 0x99, 0x93, 0x20, 0x12, 0x64, 0xf5,
	0x11, 0xc8, 0x7a, 0xb1, 0xc5, 0x62, 0xe2, 0xc8, 0x0b, 0x5c, 0x6d, 0xbe, 0xa4, 0x94, 0xe7, 0xaa,
	0xab, 0xfd, 0x9e, 0xbe, 0x2c, 0xe0, 0xb2, 0x17, 0xa2, 0x8c, 0x17, 0xa3, 0xc1, 0x48, 0x7d, 0x0c,
	0x96, 0x5c, 0x3f, 0x6c, 0x62, 0xdf, 0x6a, 0x77, 0x9a, 0xbe, 0x67, 0x5b, 0xc7, 0xe4, 0x54, 0x03,
	0xbc, 0xcc, 0x77, 0xfa, 0x3d, 0x5d, 0x13, 0x01, 0x2e, 0x41, 0x20, 0x5a, 0x14, 0xb6, 0x3d, 0x6e,
	0xda, 0x26, 0xa7, 0xea, 0x27, 0x60, 0x21, 0xf1, 0xdb, 0x21, 0x39, 0x3a, 0x8a, 0xb5, 0x4c, 0x29,
	0x55, 0xce, 0x56, 0xb5, 0x7e, 0x4f, 0x5f, 0x11, 0x51, 0xc6, 0xdc, 0x10, 0x65, 0xc5, 0x78, 0x53,
	0x0c, 0x2f, 0x52, 0x60, 0xb1, 0xb6, 0x5d, 0x47, 0xc4, 0xf5, 0x62, 0x1a, 0x61, 0xea, 0x85, 0xc1,
	0x48, 0x77, 0xca, 0xab, 0x75, 0xf7, 0x19, 0xc8, 0x75, 0xb1, 0xef, 0x39, 0x98, 0x86, 0x91, 0x85,
	0x1d, 0x27, 0xe2, 0x42, 0x1d, 0xdb, 0xe3, 0x71, 0x3f, 0x44, 0x0b, 0x43, 0x43, 0xc5, 0x71, 0x22,
	0x36, 0x93, 0x17, 0x38, 0xe4, 0x29, 0x17, 0xeb, 0xd8, 0x4c, 0xdc, 0x0c, 0x91, 0x70, 0xab, 0xef,
	0x83, 0x8c, 0x73, 0xec, 0xb2, 0x42, 0xf0, 0x42, 0x09, 0x3d, 0xde, 0xec, 0xf7, 0x74, 0x55, 0xa0,
	0x25, 0x27, 0x44, 0xf3, 0xce, 0xb1, 0xbb, 0xd7, 0x69, 0xb2, 0xe2, 0x7c, 0x08, 0xb2, 0xec, 0x80,
	0x0d, 0x89, 0x69, 0x4e, 0x94, 0xb6, 0x48, 0xf6, 0x42, 0x04, 0xd8, 0x30, 0xa1, 0x7e, 0xcc, 0xeb,
	0xca, 0xec, 0x16, 0xdb, 0x34, 0xc2, 0x75, 0x38, 0x59, 0xd7, 0x91, 0x1b, 0xa2, 0x4c, 0x9b, 0x13,
	0x1b, 0x6c, 0xc4, 0x4a, 0x43, 0x02, 0xdb, 0xc7, 0x5d, 0x62, 0x45, 0xa4, 0x1d, 0x46, 0x94, 0x4b,
	0x33, 0x2b, 0x97, 0x66, 0xdc, 0x0f, 0xd1, 0x42, 0x62, 0x40, 0x7c, 0xac, 0x6e, 0x83, 0xd9, 0x98,
	0x62, 0xda, 0x89, 0x13, 0x91, 0x96, 0x5e, 0x22, 0x52, 0x44, 0xdc, 0x06, 0xc7, 0x55, 0x97, 0xfa,
	0x3d, 0x7d, 0x61, 0x28, 0x54, 0xda, 0x89, 0x21, 0x4a, 0x42, 0xc0, 0x1f, 0x15, 0x90, 0xdb, 0x37,
	0x8c, 0x83, 0xb6, 0x1b, 0x61, 0x87, 0x98, 0xc1, 0x51, 0xf8, 0xdf, 0x74, 0x28, 0x13, 0x2c, 0xf1,
	0x43, 0xcb, 0x75, 0x33, 0x68, 0x3c, 0xd3, 0xbc, 0xf1, 0x48, 0x32, 0xbe, 0x04, 0x81, 0x28, 0x3f,
	0xb2, 0x89, 0xbe, 0x03, 0x7f, 0x55, 0xc0, 0x82, 0x11, 0xd8, 0xd1, 0x69, 0x9b, 0x12, 0xa7, 0x46,
	0xb0, 0xaf, 0x96, 0xc1, 0xac, 0xd3, 0xe2, 0xdb, 0x26, 0x16, 0x26, 0xe5, 0x27, 0xec, 0x10, 0xa5,
	0x9d, 0x16, 0xdb, 0xab, 0x0d, 0x30, 0x1f, 0x7b, 0x6e, 0x80, 0x69, 0x27, 0x22, 0x7c, 0xfa, 0xac,
	0xdc, 0x03, 0x86, 0x2e, 0x88, 0x46, 0x30, 0x26, 0xbd, 0x20, 0x0c, 0x6c, 0xc2, 0xa5, 0x97, 0x95,
	0xa5, 0xc7, 0xcd, 0x10, 0x09, 0xb7, 0x7a, 0x17, 0xcc, 0xda, 0x5e, 0xbb, 0x45, 0xa2, 0x44, 0x75,
	0xd2, 0x2a, 0x84, 0x1d, 0xa2, 0x04, 0x00, 0xff, 0x52, 0xc0, 0x0c, 0x5f, 0xf9, 0x50, 0xd6, 0xca,
	0xab, 0x65, 0xbd, 0x09, 0x16, 0x23, 0x62, 0x7b, 0x6d, 0x8f, 0x04, 0xd4, 0x12, 0x0c, 0xd1, 0xea,
	0xa5, 0x3d, 0x98, 0x00, 0x40, 0x94, 0x1b, 0x5a, 0x4c, 0x1e, 0xe4, 0x73, 0x30, 0xe3, 0x10, 0xec,
	0xf3, 0x3c, 0x32, 0x1b, 0x6f, 0x5c, 0x25, 0x93, 0xb1, 0xba, 0x56, 0x97, 0x9f, 0xf5, 0xf4, 0xa9,
	0x7e, 0x4f, 0xcf, 0x24, 0xb5, 0x24, 0xac, 0x9b, 0xf2, 0x18, 0xe3, 0x85, 0x9c, 0xb9, 0x56, 0x21,
	0xe1, 0xb7, 0x60, 0x7e, 0x33, 0x3c, 0x69, 0xfb, 0xd8, 0x0b, 0x28, 0xeb, 0x89, 0x2c, 0x10, 0x89,
	0x2c, 0xb9, 0x00, 0xd2, 0x81, 0x93, 0xbd, 0x10, 0x65, 0xc4, 0x50, 0x24, 0xf2, 0x1a, 0xbb, 0x08,
	0xff, 0x98, 0x06, 0xb9, 0x1a, 0xe1, 0xd9, 0x21, 0xf2, 0x55, 0x87, 0xc4, 0x94, 0x85, 0x89, 0xc4,
	0x4f, 0x12, 0xf1, 0xf9, 0xe7, 0xe5, 0x30, 0x43, 0x17, 0x44, 0x23, 0xd8, 0xb5, 0x6f, 0xda, 0x2b,
	0x0e, 0x4d, 0xea, 0x5f, 0x1f, 0x9a, 0x87, 0x00, 0x08, 0xc1, 0x50, 0xf2, 0x94, 0x26, 0x55, 0xbe,
	0xd1, 0xef, 0xe9, 0x4b, 0xb2, 0xaa, 0x98, 0x8f, 0x35, 0xa4, 0xe1, 0x80, 0xad, 0xd1, 0xc7, 0x4d,
	0xe2, 0x27, 0x4d, 0x4c, 0x5a, 0x23, 0x37, 0x43, 0x24, 0xdc, 0xec, 0x6a, 0x19, 0x26, 0x36, 0x6c,
	0x7c, 0xb3, 0x93, 0x57, 0xcb, 0x25, 0x08, 0x44, 0x8b, 0x43, 0x9b, 0x68, 0x81, 0xf0, 0x7b, 0x05,
	0xcc, 0x21, 0x12, 0xb7, 0xc3, 0x20, 0x26, 0xd7, 0xd6, 0xf4, 0x97, 0x20, 0xdb, 0x8d, 0xf9, 0xc5,
	0xc7, 0x79, 0xbc, 0xa2, 0x99, 0x0d, 0xfd, 0x2a, 0x59, 0x1e, 0x36, 0x1a, 0x83, 0xf0, 0xb2, 0x44,
	0x64, 0x3a, 0x44, 0x99, 0x6e, 0x1c, 0x0f, 0x50, 0xf0, 0x37, 0x05, 0x64, 0x24, 0x96, 0xfa, 0x00,
	0x80, 0x98, 0xc4, 0x31, 0xeb, 0x2c, 0x9e, 0x93, 0xb4, 0x09, 0xa9, 0x94, 0x23, 0x1f, 0x13, 0x8d,
	0x18, 0x98, 0xce, 0x28, 0x95, 0xe9, 0x57, 0xa7, 0x72, 0x77, 0xd8, 0x82, 0x53, 0xfc, 0x6a, 0x7f,
	0x79, 0x83, 0x7d, 0xad, 0x83, 0xf3, 0x2e, 0x98, 0x6d, 0xd8, 0xd8, 0xc7, 0x91, 0xfa, 0x26, 0x98,
	0x71, 0x30, 0xc5, 0x49, 0x02, 0x8b, 0xd2, 0xd9, 0xc4, 0x14, 0xb3, 0xb3, 0xc9, 0xfe, 0xbd, 0x03,
	0xd2, 0x7b, 0x21, 0x3b, 0x63, 0xd7, 0x41, 0xdf, 0xfb, 0x5b, 0x01, 0x59, 0xf9, 0x76, 0x50, 0x3f,
	0x02, 0x85, 0xda, 0x76, 0xdd, 0x42, 0x46, 0xdd, 0x6a, 0xec, 0x57, 0xf6, 0x0f, 0x1a, 0xd6, 0xc1,
	0x6e, 0x63, 0xcf, 0xd8, 0x34, 0xb7, 0x4c, 0xa3, 0x96, 0x9f, 0x2a, 0xdc, 0x3e, 0x3b, 0x2f, 0xad,
	0xca, 0x8c, 0x83, 0x20, 0x6e, 0x13, 0xdb, 0x3b, 0xf2, 0x88, 0xa3, 0x3e, 0x04, 0xab, 0x13, 0xe4,
	0x43, 0x03, 0x09, 0xa6, 0x52, 0xd0, 0xce, 0xce, 0x4b, 0x2b, 0x32, 0xf3, 0x90, 0x44, 0x82, 0xf6,
	0x01, 0xd0, 0x26, 0x68, 0x5b, 0xe6, 0x6e, 0x65, 0xc7, 0x7c, 0x62, 0xd4, 0xf2, 0xd3, 0x85, 0x5b,
	0x67, 0xe7, 0xa5, 0x1b, 0x32, 0x6f, 0xcb, 0x0b, 0xb0, 0xef, 0x7d, 0x43, 0x9c, 0x2b, 0x16, 0x6b,
	0xee, 0x1e, 0x56, 0x76, 0xcc, 0x5a, 0x65, 0xdf, 0xa8, 0xe5, 0x53, 0x97, 0x17, 0x6b, 0x06, 0xc9,
	0xc3, 0x82, 0x38, 0x85, 0x99, 0xef, 0x7e, 0x2a, 0x4e, 0xdd, 0xfb, 0x79, 0x1a, 0xcc, 0x0d, 0xde,
	0x70, 0xea, 0x06, 0x60, 0x13, 0xb1, 0x58, 0x75, 0x63, 0x22, 0xef, 0xd5, 0xb3, 0xf3, 0xd2, 0xf2,
	0x00, 0x28, 0xe7, 0xfc, 0x00, 0xdc, 0x1c, 0x71, 0x90, 0x51, 0x37, 0x1b, 0xfb, 0xa8, 0xb2, 0x6f,
	0x7e, 0xb1, 0x2b, 0xa5, 0xcc, 0x49, 0x63, 0x6f, 0xa7, 0x7b, 0x60, 0x69, 0xc4, 0xaa, 0x19, 0x95,
	0x1d, 0x73, 0xb7, 0x9e, 0x9f, 0x2e, 0x2c, 0x9f, 0x9d, 0x97, 0x16, 0x07, 0x04, 0xd6, 0x85, 0xd9,
	0x23, 0x70, 0x6c, 0x86, 0xa4, 0x32, 0x62, 0x86, 0xd4, 0xf8, 0x0c, 0x49, 0x61, 0xc4, 0x0c, 0x65,
	0x90, 0x1f, 0xb1, 0x2a, 0x9b, 0xfb, 0xe6, 0xa1, 0x91, 0x9f, 0x29, 0xa8, 0x67, 0xe7, 0xa5, 0xdc,
	0x00, 0x5f, 0xe1, 0x0f, 0xe9, 0x71, 0xe4, 0x56, 0xc5, 0xdc, 0x31, 0x6a, 0xf9, 0xf4, 0x38, 0x72,
	0x0b, 0x7b, 0xfe, 0xa0, 0x64, 0x55, 0xe3, 0xd9, 0x8b, 0xa2, 0xf2, 0xfc, 0x45, 0x51, 0xf9, 0xf3,
	0x45, 0x51, 0xf9, 0xe1, 0xa2, 0x38, 0xf5, 0xfc, 0xa2, 0x38, 0xf5, 0xfb, 0x45, 0x71, 0xea, 0xc9,
	0xdb, 0xae, 0x47, 0x5b, 0x9d, 0xe6, 0x9a, 0x1d, 0x9e, 0xac, 0xb7, 0xbd, 0xb6, 0x8f, 0x9b, 0xf1,
	0xba, 0xf8, 0x74, 0xb2, 0x7d, 0x76, 0x13, 0xad, 0x3f, 0xe5, 0xdf, 0x50, 0xfc, 0x58, 0x37, 0x67,
	0xf9, 0x17, 0xd1, 0x7b, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x46, 0x49, 0x44, 0xa3, 0x5d, 0x0d,
	0x00, 0x00,
}

func (m *DKGNetwork) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DKGNetwork) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DKGNetwork) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PublicCoeffs) > 0 {
		for iNdEx := len(m.PublicCoeffs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PublicCoeffs[iNdEx])
			copy(dAtA[i:], m.PublicCoeffs[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.PublicCoeffs[iNdEx])))
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.GlobalPublicKey) > 0 {
		i -= len(m.GlobalPublicKey)
		copy(dAtA[i:], m.GlobalPublicKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.GlobalPublicKey)))
		i--
		dAtA[i] = 0x52
	}
	if m.IsResharing {
		i--
		if m.IsResharing {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.Stage != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Stage))
		i--
		dAtA[i] = 0x40
	}
	if m.Threshold != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Threshold))
		i--
		dAtA[i] = 0x38
	}
	if m.Total != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ActiveValSet) > 0 {
		for iNdEx := len(m.ActiveValSet) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ActiveValSet[iNdEx])
			copy(dAtA[i:], m.ActiveValSet[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.ActiveValSet[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.StartBlockHash) > 0 {
		i -= len(m.StartBlockHash)
		copy(dAtA[i:], m.StartBlockHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.StartBlockHash)))
		i--
		dAtA[i] = 0x22
	}
	if m.StartBlockHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.StartBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.Round != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x10
	}
	if len(m.CodeCommitment) > 0 {
		i -= len(m.CodeCommitment)
		copy(dAtA[i:], m.CodeCommitment)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CodeCommitment)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DKGRegistration) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DKGRegistration) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DKGRegistration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x40
	}
	if len(m.EnclaveReport) > 0 {
		i -= len(m.EnclaveReport)
		copy(dAtA[i:], m.EnclaveReport)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.EnclaveReport)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.PubKeyShare) > 0 {
		i -= len(m.PubKeyShare)
		copy(dAtA[i:], m.PubKeyShare)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PubKeyShare)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CommPubKey) > 0 {
		i -= len(m.CommPubKey)
		copy(dAtA[i:], m.CommPubKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CommPubKey)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.DkgPubKey) > 0 {
		i -= len(m.DkgPubKey)
		copy(dAtA[i:], m.DkgPubKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DkgPubKey)))
		i--
		dAtA[i] = 0x22
	}
	if m.Index != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ValidatorAddr) > 0 {
		i -= len(m.ValidatorAddr)
		copy(dAtA[i:], m.ValidatorAddr)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ValidatorAddr)))
		i--
		dAtA[i] = 0x12
	}
	if m.Round != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TEEUpgradeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TEEUpgradeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TEEUpgradeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActivationHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ActivationHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.CodeCommitment) > 0 {
		i -= len(m.CodeCommitment)
		copy(dAtA[i:], m.CodeCommitment)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CodeCommitment)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EncryptedDeal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EncryptedDeal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EncryptedDeal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Cipher) > 0 {
		i -= len(m.Cipher)
		copy(dAtA[i:], m.Cipher)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Cipher)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DhKey) > 0 {
		i -= len(m.DhKey)
		copy(dAtA[i:], m.DhKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DhKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Deal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Deal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Deal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Deal.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.RecipientIndex != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RecipientIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.Index != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Complaint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Complaint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Complaint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if m.DealerIndex != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.DealerIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DecryptRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DecryptRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DecryptRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequesterPubKey) > 0 {
		i -= len(m.RequesterPubKey)
		copy(dAtA[i:], m.RequesterPubKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RequesterPubKey)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Label) > 0 {
		i -= len(m.Label)
		copy(dAtA[i:], m.Label)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Label)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Ciphertext) > 0 {
		i -= len(m.Ciphertext)
		copy(dAtA[i:], m.Ciphertext)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Ciphertext)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CodeCommitment) > 0 {
		i -= len(m.CodeCommitment)
		copy(dAtA[i:], m.CodeCommitment)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CodeCommitment)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Round != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Requester) > 0 {
		i -= len(m.Requester)
		copy(dAtA[i:], m.Requester)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Requester)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Response) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VssResponse != nil {
		{
			size, err := m.VssResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VSSResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VSSResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VSSResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x22
	}
	if m.Status {
		i--
		if m.Status {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Index != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SessionId) > 0 {
		i -= len(m.SessionId)
		copy(dAtA[i:], m.SessionId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SessionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Scalar) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Scalar) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Scalar) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Point) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Point) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Point) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DKGNetwork) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CodeCommitment)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovTypes(uint64(m.Round))
	}
	if m.StartBlockHeight != 0 {
		n += 1 + sovTypes(uint64(m.StartBlockHeight))
	}
	l = len(m.StartBlockHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.ActiveValSet) > 0 {
		for _, s := range m.ActiveValSet {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Total != 0 {
		n += 1 + sovTypes(uint64(m.Total))
	}
	if m.Threshold != 0 {
		n += 1 + sovTypes(uint64(m.Threshold))
	}
	if m.Stage != 0 {
		n += 1 + sovTypes(uint64(m.Stage))
	}
	if m.IsResharing {
		n += 2
	}
	l = len(m.GlobalPublicKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.PublicCoeffs) > 0 {
		for _, b := range m.PublicCoeffs {
			l = len(b)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *DKGRegistration) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Round != 0 {
		n += 1 + sovTypes(uint64(m.Round))
	}
	l = len(m.ValidatorAddr)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovTypes(uint64(m.Index))
	}
	l = len(m.DkgPubKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CommPubKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.PubKeyShare)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.EnclaveReport)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	return n
}

func (m *TEEUpgradeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CodeCommitment)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ActivationHeight != 0 {
		n += 1 + sovTypes(uint64(m.ActivationHeight))
	}
	return n
}

func (m *EncryptedDeal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DhKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Cipher)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Deal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovTypes(uint64(m.Index))
	}
	if m.RecipientIndex != 0 {
		n += 1 + sovTypes(uint64(m.RecipientIndex))
	}
	l = m.Deal.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Complaint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DealerIndex != 0 {
		n += 1 + sovTypes(uint64(m.DealerIndex))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *DecryptRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Requester)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovTypes(uint64(m.Round))
	}
	l = len(m.CodeCommitment)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Ciphertext)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Label)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.RequesterPubKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Response) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovTypes(uint64(m.Index))
	}
	if m.VssResponse != nil {
		l = m.VssResponse.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *VSSResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SessionId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovTypes(uint64(m.Index))
	}
	if m.Status {
		n += 2
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Scalar) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Point) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DKGNetwork) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DKGNetwork: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DKGNetwork: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeCommitment = append(m.CodeCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.CodeCommitment == nil {
				m.CodeCommitment = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlockHeight", wireType)
			}
			m.StartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartBlockHash = append(m.StartBlockHash[:0], dAtA[iNdEx:postIndex]...)
			if m.StartBlockHash == nil {
				m.StartBlockHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveValSet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActiveValSet = append(m.ActiveValSet, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threshold", wireType)
			}
			m.Threshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Threshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stage", wireType)
			}
			m.Stage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stage |= DKGStage(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsResharing", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsResharing = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalPublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GlobalPublicKey = append(m.GlobalPublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.GlobalPublicKey == nil {
				m.GlobalPublicKey = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicCoeffs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicCoeffs = append(m.PublicCoeffs, make([]byte, postIndex-iNdEx))
			copy(m.PublicCoeffs[len(m.PublicCoeffs)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DKGRegistration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DKGRegistration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DKGRegistration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DkgPubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DkgPubKey = append(m.DkgPubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.DkgPubKey == nil {
				m.DkgPubKey = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommPubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommPubKey = append(m.CommPubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.CommPubKey == nil {
				m.CommPubKey = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKeyShare", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKeyShare = append(m.PubKeyShare[:0], dAtA[iNdEx:postIndex]...)
			if m.PubKeyShare == nil {
				m.PubKeyShare = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnclaveReport", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnclaveReport = append(m.EnclaveReport[:0], dAtA[iNdEx:postIndex]...)
			if m.EnclaveReport == nil {
				m.EnclaveReport = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= DKGRegStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TEEUpgradeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TEEUpgradeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TEEUpgradeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeCommitment = append(m.CodeCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.CodeCommitment == nil {
				m.CodeCommitment = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationHeight", wireType)
			}
			m.ActivationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EncryptedDeal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EncryptedDeal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EncryptedDeal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DhKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DhKey = append(m.DhKey[:0], dAtA[iNdEx:postIndex]...)
			if m.DhKey == nil {
				m.DhKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = append(m.Nonce[:0], dAtA[iNdEx:postIndex]...)
			if m.Nonce == nil {
				m.Nonce = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cipher", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cipher = append(m.Cipher[:0], dAtA[iNdEx:postIndex]...)
			if m.Cipher == nil {
				m.Cipher = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Deal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Deal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Deal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientIndex", wireType)
			}
			m.RecipientIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecipientIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Deal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Complaint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Complaint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Complaint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealerIndex", wireType)
			}
			m.DealerIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DealerIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DecryptRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DecryptRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DecryptRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requester", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requester = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeCommitment = append(m.CodeCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.CodeCommitment == nil {
				m.CodeCommitment = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ciphertext", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ciphertext = append(m.Ciphertext[:0], dAtA[iNdEx:postIndex]...)
			if m.Ciphertext == nil {
				m.Ciphertext = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Label = append(m.Label[:0], dAtA[iNdEx:postIndex]...)
			if m.Label == nil {
				m.Label = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequesterPubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequesterPubKey = append(m.RequesterPubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.RequesterPubKey == nil {
				m.RequesterPubKey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VssResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VssResponse == nil {
				m.VssResponse = &VSSResponse{}
			}
			if err := m.VssResponse.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VSSResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VSSResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VSSResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionId = append(m.SessionId[:0], dAtA[iNdEx:postIndex]...)
			if m.SessionId == nil {
				m.SessionId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Status = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Scalar) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Scalar: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Scalar: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Point) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Point: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Point: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
