// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: v1/tee.proto

package dkg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TEE_GenerateAndSealKey_FullMethodName = "/story.dkg.v1.tee.TEE/GenerateAndSealKey"
	TEE_VerifyRawQuote_FullMethodName     = "/story.dkg.v1.tee.TEE/VerifyRawQuote"
	TEE_SetupDKGNetwork_FullMethodName    = "/story.dkg.v1.tee.TEE/SetupDKGNetwork"
	TEE_GenerateDeals_FullMethodName      = "/story.dkg.v1.tee.TEE/GenerateDeals"
	TEE_ProcessDeals_FullMethodName       = "/story.dkg.v1.tee.TEE/ProcessDeals"
	TEE_ProcessResponses_FullMethodName   = "/story.dkg.v1.tee.TEE/ProcessResponses"
	TEE_FinalizeDKG_FullMethodName        = "/story.dkg.v1.tee.TEE/FinalizeDKG"
)

// TEEClient is the client API for TEE service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TEEClient interface {
	GenerateAndSealKey(ctx context.Context, in *GenerateAndSealKeyRequest, opts ...grpc.CallOption) (*GenerateAndSealKeyResponse, error)
	VerifyRawQuote(ctx context.Context, in *VerifyRawQuoteRequest, opts ...grpc.CallOption) (*VerifyRawQuoteResponse, error)
	SetupDKGNetwork(ctx context.Context, in *SetupDKGNetworkRequest, opts ...grpc.CallOption) (*SetupDKGNetworkResponse, error)
	GenerateDeals(ctx context.Context, in *GenerateDealsRequest, opts ...grpc.CallOption) (*GenerateDealsResponse, error)
	ProcessDeals(ctx context.Context, in *ProcessDealRequest, opts ...grpc.CallOption) (*ProcessDealResponse, error)
	ProcessResponses(ctx context.Context, in *ProcessResponsesRequest, opts ...grpc.CallOption) (*ProcessResponsesResponse, error)
	FinalizeDKG(ctx context.Context, in *FinalizeDKGRequest, opts ...grpc.CallOption) (*FinalizeDKGResponse, error)
}

type tEEClient struct {
	cc grpc.ClientConnInterface
}

func NewTEEClient(cc grpc.ClientConnInterface) TEEClient {
	return &tEEClient{cc}
}

func (c *tEEClient) GenerateAndSealKey(ctx context.Context, in *GenerateAndSealKeyRequest, opts ...grpc.CallOption) (*GenerateAndSealKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateAndSealKeyResponse)
	err := c.cc.Invoke(ctx, TEE_GenerateAndSealKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tEEClient) VerifyRawQuote(ctx context.Context, in *VerifyRawQuoteRequest, opts ...grpc.CallOption) (*VerifyRawQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyRawQuoteResponse)
	err := c.cc.Invoke(ctx, TEE_VerifyRawQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tEEClient) SetupDKGNetwork(ctx context.Context, in *SetupDKGNetworkRequest, opts ...grpc.CallOption) (*SetupDKGNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupDKGNetworkResponse)
	err := c.cc.Invoke(ctx, TEE_SetupDKGNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tEEClient) GenerateDeals(ctx context.Context, in *GenerateDealsRequest, opts ...grpc.CallOption) (*GenerateDealsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDealsResponse)
	err := c.cc.Invoke(ctx, TEE_GenerateDeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tEEClient) ProcessDeals(ctx context.Context, in *ProcessDealRequest, opts ...grpc.CallOption) (*ProcessDealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDealResponse)
	err := c.cc.Invoke(ctx, TEE_ProcessDeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tEEClient) ProcessResponses(ctx context.Context, in *ProcessResponsesRequest, opts ...grpc.CallOption) (*ProcessResponsesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponsesResponse)
	err := c.cc.Invoke(ctx, TEE_ProcessResponses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tEEClient) FinalizeDKG(ctx context.Context, in *FinalizeDKGRequest, opts ...grpc.CallOption) (*FinalizeDKGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeDKGResponse)
	err := c.cc.Invoke(ctx, TEE_FinalizeDKG_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TEEServer is the server API for TEE service.
// All implementations must embed UnimplementedTEEServer
// for forward compatibility.
type TEEServer interface {
	GenerateAndSealKey(context.Context, *GenerateAndSealKeyRequest) (*GenerateAndSealKeyResponse, error)
	VerifyRawQuote(context.Context, *VerifyRawQuoteRequest) (*VerifyRawQuoteResponse, error)
	SetupDKGNetwork(context.Context, *SetupDKGNetworkRequest) (*SetupDKGNetworkResponse, error)
	GenerateDeals(context.Context, *GenerateDealsRequest) (*GenerateDealsResponse, error)
	ProcessDeals(context.Context, *ProcessDealRequest) (*ProcessDealResponse, error)
	ProcessResponses(context.Context, *ProcessResponsesRequest) (*ProcessResponsesResponse, error)
	FinalizeDKG(context.Context, *FinalizeDKGRequest) (*FinalizeDKGResponse, error)
	mustEmbedUnimplementedTEEServer()
}

// UnimplementedTEEServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTEEServer struct{}

func (UnimplementedTEEServer) GenerateAndSealKey(context.Context, *GenerateAndSealKeyRequest) (*GenerateAndSealKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAndSealKey not implemented")
}
func (UnimplementedTEEServer) VerifyRawQuote(context.Context, *VerifyRawQuoteRequest) (*VerifyRawQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyRawQuote not implemented")
}
func (UnimplementedTEEServer) SetupDKGNetwork(context.Context, *SetupDKGNetworkRequest) (*SetupDKGNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupDKGNetwork not implemented")
}
func (UnimplementedTEEServer) GenerateDeals(context.Context, *GenerateDealsRequest) (*GenerateDealsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDeals not implemented")
}
func (UnimplementedTEEServer) ProcessDeals(context.Context, *ProcessDealRequest) (*ProcessDealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessDeals not implemented")
}
func (UnimplementedTEEServer) ProcessResponses(context.Context, *ProcessResponsesRequest) (*ProcessResponsesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessResponses not implemented")
}
func (UnimplementedTEEServer) FinalizeDKG(context.Context, *FinalizeDKGRequest) (*FinalizeDKGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeDKG not implemented")
}
func (UnimplementedTEEServer) mustEmbedUnimplementedTEEServer() {}
func (UnimplementedTEEServer) testEmbeddedByValue()             {}

// UnsafeTEEServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TEEServer will
// result in compilation errors.
type UnsafeTEEServer interface {
	mustEmbedUnimplementedTEEServer()
}

func RegisterTEEServer(s grpc.ServiceRegistrar, srv TEEServer) {
	// If the following call pancis, it indicates UnimplementedTEEServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TEE_ServiceDesc, srv)
}

func _TEE_GenerateAndSealKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAndSealKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServer).GenerateAndSealKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEE_GenerateAndSealKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServer).GenerateAndSealKey(ctx, req.(*GenerateAndSealKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TEE_VerifyRawQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRawQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServer).VerifyRawQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEE_VerifyRawQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServer).VerifyRawQuote(ctx, req.(*VerifyRawQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TEE_SetupDKGNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupDKGNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServer).SetupDKGNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEE_SetupDKGNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServer).SetupDKGNetwork(ctx, req.(*SetupDKGNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TEE_GenerateDeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServer).GenerateDeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEE_GenerateDeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServer).GenerateDeals(ctx, req.(*GenerateDealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TEE_ProcessDeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServer).ProcessDeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEE_ProcessDeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServer).ProcessDeals(ctx, req.(*ProcessDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TEE_ProcessResponses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessResponsesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServer).ProcessResponses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEE_ProcessResponses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServer).ProcessResponses(ctx, req.(*ProcessResponsesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TEE_FinalizeDKG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeDKGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServer).FinalizeDKG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEE_FinalizeDKG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServer).FinalizeDKG(ctx, req.(*FinalizeDKGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TEE_ServiceDesc is the grpc.ServiceDesc for TEE service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TEE_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "story.dkg.v1.tee.TEE",
	HandlerType: (*TEEServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAndSealKey",
			Handler:    _TEE_GenerateAndSealKey_Handler,
		},
		{
			MethodName: "VerifyRawQuote",
			Handler:    _TEE_VerifyRawQuote_Handler,
		},
		{
			MethodName: "SetupDKGNetwork",
			Handler:    _TEE_SetupDKGNetwork_Handler,
		},
		{
			MethodName: "GenerateDeals",
			Handler:    _TEE_GenerateDeals_Handler,
		},
		{
			MethodName: "ProcessDeals",
			Handler:    _TEE_ProcessDeals_Handler,
		},
		{
			MethodName: "ProcessResponses",
			Handler:    _TEE_ProcessResponses_Handler,
		},
		{
			MethodName: "FinalizeDKG",
			Handler:    _TEE_FinalizeDKG_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/tee.proto",
}
