package types

// evmstaking module event types.
const (
	EventTypeUpdateValidatorCommissionFailure = "update_validator_commission_failure"
	EventTypeSetWithdrawalAddressFailure      = "set_withdrawal_address_failure"
	EventTypeSetRewardAddressFailure          = "set_reward_address_failure"
	EventTypeSetOperatorFailure               = "set_operator_failure"
	EventTypeUnsetOperatorFailure             = "unset_operator_failure"
	EventTypeCreateValidatorFailure           = "create_validator_failure"
	EventTypeDelegateFailure                  = "delegate_failure"
	EventTypeRedelegateFailure                = "redelegate_failure"
	EventTypeUndelegateFailure                = "undelegate_failure"
	EventTypeUnjailFailure                    = "unjail_failure"
	EventTypeWithdraw                         = "withdraw"

	EventTypeUpdateValidatorCommissionSuccess = "update_validator_commission_success"
	EventTypeSetWithdrawalAddressSuccess      = "set_withdrawal_address_success"
	EventTypeSetRewardAddressSuccess          = "set_reward_address_success"
	EventTypeSetOperatorSuccess               = "set_operator_success"
	EventTypeUnsetOperatorSuccess             = "unset_operator_success"
	EventTypeCreateValidatorSuccess           = "create_validator_success"
	EventTypeDelegateSuccess                  = "delegate_success"
	EventTypeRedelegateSuccess                = "redelegate_success"
	EventTypeUndelegateSuccess                = "undelegate_success"
	EventTypeUnjailSuccess                    = "unjail_success"

	AttributeKeyErrorCode                  = "error_code"
	AttributeKeyBlockHeight                = "block_height"
	AttributeKeyTxHash                     = "tx_hash"
	AttributeKeyDelegatorAddress           = "delegator_addr"
	AttributeKeyValidatorCmpPubKey         = "validator_cmp_pubkey"
	AttributeKeySrcValidatorCmpPubKey      = "src_validator_cmp_pubkey"
	AttributeKeyDstValidatorCmpPubKey      = "dst_validator_cmp_pubkey"
	AttributeKeyDelegateID                 = "delegation_id"
	AttributeKeyPeriodType                 = "staking_period"
	AttributeKeyAmount                     = "amount"
	AttributeKeySenderAddress              = "sender_address"
	AttributeKeyWithdrawalAddress          = "withdrawal_address"
	AttributeKeyRewardAddress              = "reward_address"
	AttributeKeyOperatorAddress            = "operator_address"
	AttributeKeyMoniker                    = "moniker"
	AttributeKeyCommissionRate             = "commission_rate"
	AttributeKeyMaxCommissionRate          = "max_commission_rate"
	AttributeKeyMaxCommissionChangeRate    = "max_commission_change_rate"
	AttributeKeyTokenType                  = "token_type"
	AttributeKeyWithdrawalCreationHeight   = "creation_height"
	AttributeKeyWithdrawalExecAddress      = "withdraw_execution_address"
	AttributeKeyWithdrawalType             = "withdrawal_type"
	AttributeKeyWithdrawalValidatorAddress = "withdrawal_validator_address"
)
