name: Build and Push to Docker Hub

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  # Build and upload the geth binary
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set build arguments
        run: |
          echo "REPOSITORY_URI=${{ vars.REPOSITORY_URI }}" >> $GITHUB_ENV
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "BUILDNUM=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Dockerize the geth and bootnode binary
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm64/v8 \
            --build-arg BUILDNUM=$BUILDNUM \
            --build-arg COMMIT=$COMMIT \
            --build-arg VERSION=$VERSION \
            -t $REPOSITORY_URI:latest \
            -t $REPOSITORY_URI:$COMMIT \
            -t $REPOSITORY_URI:$VERSION \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --push \
            -f ./Dockerfile \
            .
